<?php 
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet purple box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-cogs"></i>Services List </div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/services', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Service </a> </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm yellow table-group-action-submit changeStatus"><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
			<table class="table table-hover table-bordered table-striped">
				<thead>
					<tr>
						<th>Service Category</th>
						<th>Service Period</th>
						<th>Description</th>
						<th>Status</th>
						<th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
					</tr>
				</thead>
				<tbody>
				<?php if (isset($services) && count($services)>0) : ?>
					<?php foreach ($services as $service) : ?>
					<tr>
						<td><?php echo $this->escapeHtml($service->category_name);?></td>
						<td><?php echo $this->escapeHtml($service->service_period." mins");?></td>
						<td><?php echo substr($this->escapeHtml($service->description),0,50);?></td>
						<td><span class="label label-sm label-<?php echo (array_key_exists($service->status_id, $statusArray))?$statusArray[$service->status_id]:'default';?>" id="<?php echo $service->id;?>"><?php echo $this->escapeHtml(ucwords($service->status));?></span></td>
						<td>
							<a class="btn default btn-xs blue" href="<?php echo $this->url('admin/services',array('action'=>'edit', 'id' => $service->id));?>"><i class="fa fa-edit"></i> Edit</a>
							<a class="btn default btn-xs red" href="<?php echo $this->url('admin/services',array('action'=>'delete', 'id' => $service->id));?>"><i class="fa fa-trash-o"></i> Delete</a>
							<input class="checkboxes" type="checkbox" value="<?php echo $service->id;?>">
						</td>
					</tr>
					<?php endforeach; ?>
				<?php endif; ?>
				</tbody>
			</table>
		<?php echo $this->paginationControl(
						$services,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/services')  // the route to link to when a user clicks a control link
					);
		?>
		</div>
      </div>
    </div>
  </div>
</div> 
