<?php
$title = 'Add New Notification';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/notificationsettings', array('action' => 'add')));
$form->prepare();

?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/notificationsettings"> <i class="fa fa-pencil"></i>Notifications List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
    <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<h3 class="form-section">Notification Info</h3>
			<div class="row">
				<?php $user_id = $form->get('user_id'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($user_id) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($user_id); ?></label>
					<div class="col-md-11">
						<?php echo $this->formSelect($user_id); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($user_id); ?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $module_id = $form->get('module_id'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($module_id) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($module_id); ?></label>
					<div class="col-md-11">
						<?php echo $this->formSelect($module_id); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($module_id); ?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $sms_flag = $form->get('sms_flag'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($sms_flag) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($sms_flag); ?></label>
					<div class="col-md-11">
						<?php echo $this->formCheckbox($sms_flag); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($sms_flag); ?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $email_flag = $form->get('email_flag'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($email_flag) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($email_flag); ?></label>
					<div class="col-md-11">
						<?php echo $this->formCheckbox($email_flag); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($email_flag); ?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $page_alert_flag = $form->get('page_alert_flag'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($page_alert_flag) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($page_alert_flag); ?></label>
					<div class="col-md-11">
						<?php echo $this->formCheckbox($page_alert_flag); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($page_alert_flag); ?>
						</span>
					</div>
				</div>
			</div>
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
	</div>
</div>
