<?php
$status = (isset($status) && count($status) > 0) ? $status->toArray() : array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
    <div class="col-md-12 col-sm-12">

        <?php if (isset($successMsgs) && count($successMsgs) > 0): ?>
            <div class="note note-success">
                <?php
                foreach ($successMsgs as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <?php if (isset($errors) && count($errors) > 0): ?>
            <div class="note note-danger">
                <?php
                foreach ($errors as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <div class="note" id="error" style="display:none;"></div>

        <div class="portlet grey box">
            <div class="portlet-title">
                <div class="caption"> <i class="fa fa-gears"></i>Notifications List</div>
                <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/notificationsettings', array('action' => 'add')); ?>"> <i class="fa fa-pencil"></i> Add New Notification Setting </a> </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>User</th>
                                <th>Module</th>
                                <th>Sms</th>
                                <th>Email</th>
                                <th>Page Alert</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($settings) && count($settings) > 0) : ?>
                                <?php foreach ($settings as $setting) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($setting->id); ?></td>
                                        <td><?php echo $this->escapeHtml($setting->user_name); ?></td>
                                        <td><?php echo $this->escapeHtml($setting->module_name); ?></td>
                                        <td><?php if($setting->sms_flag!="1"){ echo "No"; }else{ echo "Yes"; } ?></td>
                                        <td><?php if($setting->email_flag!="1"){ echo "No"; }else{ echo "Yes"; } ?></td>
                                        <td><?php if($setting->page_alert_flag!="1"){ echo "No"; }else{ echo "Yes"; }  ?></td>
                                        <td>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/notificationsettings', array('controller' => 'notificationsettings', 'action' => 'edit', 'id' => $setting->id)); ?>"><i class="fa fa-edit" title="edit" ></i></a>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/notificationsettings', array('controller' => 'notificationsettings', 'action' => 'delete', 'id' => $setting->id)); ?>"><i class="fa fa-trash-o" title="delete" ></i></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php
                    echo
                    $this->paginationControl(
                            $settings, 'sliding', array('partial/paginator.phtml', 'Admin'), array('route' => 'admin/notificationsettings')
                    );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
