<?php $status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning');
$invoiceStatusArray= array('0' => 'danger', '1' => 'success', '2' => 'warning');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-random"></i>Subscriptions List </div>
        <div class="actions"> 
			<a class="btn default btn-sm" href="<?php echo (count($this->postedData) > 0)?$this->url('admin/subscriptions', array('action'=>'export')).'?'.http_build_query($this->postedData):$this->url('admin/subscriptions', array('action'=>'export'));?>"> <i class="fa fa-download"></i> Export </a> 
			<a class="btn default btn-sm" href="<?php echo $this->url('admin/subscriptions', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Subscription </a> 
        </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/subscriptions', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
		<table class="table table-hover table-bordered table-striped" id="subscription_table" data-path='<?php echo $this->url('admin/subscriptions');?>'>
            <thead>
				<tr>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'name') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='name'>User</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'subscription') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='subscription'>Subscription</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'start') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='start'>Start Date</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'end') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='end'>End Date</th>
					<th>Amount</th>
					<th>Currency</th>
					<th>Payment status</th>
					<th>Status</th>
					<th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
				</tr>
			</thead>
            <tbody>
			<?php if (isset($subscriptions) && count($subscriptions)>0) : ?>
				<?php foreach ($subscriptions as $subscription) :?>
				<tr>
					<td><?php echo $this->escapeHtml($subscription->first_name." ".$subscription->last_name);?></td>
					<td><?php echo $this->escapeHtml($subscription->subscription_name." - ".$subscription->duration." ".$subscription->duration_in);?></td>
					<td><?php echo $this->escapeHtml(date('d-m-Y',strtotime($subscription->subscription_start_date)));?></td>
					<td><?php echo $this->escapeHtml(date('d-m-Y',strtotime($subscription->subscription_end_date)));?></td>
					<td><?php echo $this->escapeHtml($subscription->invoice_total);?></td>
					<td><?php echo $this->escapeHtml($subscription->currency);?></td>
					<td><span class="label label-sm label-<?php  echo (array_key_exists($subscription->invoice_status, $invoiceStatusArray))?$invoiceStatusArray[$subscription->invoice_status]:'default';?>" ><?php echo $this->escapeHtml($subscription->payment_status);?></span></td>
					<td><span class="label label-sm status label-<?php echo (array_key_exists($subscription->status_id, $statusArray))?$statusArray[$subscription->status_id]:'default';?>" id="<?php echo $subscription->id;?>"><?php echo $this->escapeHtml(ucwords($subscription->status));?></span></td>
					<td>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/subscriptions',array('action'=>'edit', 'id' => $subscription->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/subscriptions',array('action'=>'delete', 'id' => $subscription->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
						<input class="checkboxes" type="checkbox" value="<?php echo $subscription->id;?>">
					</td>
				</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			</tbody>
		</table>
		<?php 
		echo $this->paginationControl(
						$subscriptions,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/subscriptions', 'routeParams' => $this->postedData)  // the route to link to when a user clicks a control link
					);
		?>
		</div>
      </div>
    </div>
  </div>
</div>
