<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/sitebanner', array('action' => 'add')));
	$form->prepare(); 
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> Add Banner </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/sitebanner/"> <i class="fa fa-list"></i> Banners List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
    <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php if (isset($file_errors) && count($file_errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($file_errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($msg))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<div class="row">
				<?php $field = $form->get('title'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($field); ?></label>
					<div class="col-md-11">
						<?php echo $this->formInput($field); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($field); ?>
						</span>
					</div>
				</div>
			</div>
                        <div class="row">
				<?php $field = $form->get('page_location_id'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($field); ?></label>
					<div class="col-md-11">
						<?php echo $this->formSelect($field); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($field); ?>
						</span>
					</div>
				</div>			
			</div>
			
			<div class="row file">
				<?php $field = $form->get('banner_url')->setAttributes(array('class' => '')); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($field); ?></label>
					<div class="col-md-9">
						<div class="fileinput fileinput-new" data-provides="fileinput">
							<span class="btn default btn-file">
								<span class="fileinput-new">
									 Select file
								</span>
								<span class="fileinput-exists">
									 Change
								</span>
								<?php echo $this->formFile($field);?>
							</span>
							<span class="fileinput-filename">
							</span>
							 &nbsp;
							<a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">
							</a>
							<span class="help-block">
								<?php echo $this->formElementErrors($field); ?>
							</span>
						</div>
					</div>
				</div>			
			</div>
			
			<div class="row">
				<?php $field = $form->get('status_id'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
					<label class="control-label col-md-1"><?php echo $this->formLabel($field); ?></label>
					<div class="col-md-11">
						<?php echo $this->formSelect($field); ?>	
						<span class="help-block">
							 <?php echo $this->formElementErrors($field); ?>
						</span>
					</div>
				</div>			
			</div>
			
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
	</div>
</div>
