<?php
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-desktop"></i>Banners List </div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/sitebanner', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Banner </a></div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
            <thead>
				<tr>
					<th>Banner Title</th>
					<th>Banner</th>
                                        <th>Page</th>
					<th>Status</th>
					<th width="161" >Action </th>
				</tr>
            </thead>
            <tbody>
              <?php if (isset($sitebanners) && count($sitebanners)>0) : ?>
              <?php foreach ($sitebanners as $sitebanner) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($sitebanner->title);?></td>
                <td><a class="btn default" data-toggle="modal" href="#image" onclick="callImage('<?php echo $this->escapeHtml($sitebanner->banner_title);?>', '<?php echo $this->escapeHtml($sitebanner->banner_url);?>')" ><img src="<?php echo $this->escapeHtml($sitebanner->banner_url);?>" height="50" width="50" ></a></td>
                <td><?php echo $this->escapeHtml($sitebanner->page_name);?></td>
                <td><span class="label label-sm label-<?php  echo (array_key_exists($sitebanner->status_id, $statusArray))?$statusArray[$sitebanner->status_id]:'default';?>" id="<?php echo $sitebanner->id;?>"><?php echo $this->escapeHtml(ucwords($sitebanner->status));?></span></td>
                <td>
					<a class="btn default btn-xs default" href="<?php echo $this->url('admin/sitebanner',array('action'=>'edit', 'booking_id' => $this->booking_id, 'id' => $sitebanner->id));?>" title='Edit'><i class="fa fa-edit"></i> </a>
					<a class="btn default btn-xs default" href="<?php echo $this->url('admin/sitebanner',array('action'=>'delete', 'booking_id' => $this->booking_id, 'id' => $sitebanner->id));?>" title='Delete'><i class="fa fa-trash-o"></i> </a>
              </tr>
              <?php endforeach; ?>
              <?php endif; ?>
            </tbody>
          </table>
          <?php 
		echo $this->paginationControl(
                        $sitebanners, // the paginator object
                        'sliding', // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        array('partial/paginator.phtml', 'Admin'), // the partial to use to render the control
                        array('route' => 'admin/sitebanner')  // the route to link to when a user clicks a control link
                );
         ?>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Image popup start -->
<div class="modal fade bs-modal-lg" id="image" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title image"></h4>
			</div>
			<div class="modal-body">
				<img src="" style="width:100%" />
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- image popup end -->