<?php
$title = 'Delete Feedback'; 
$this->headTitle($title);
?>
<div class="col-md-6">
  <div class="portlet box grey">
    <div class="portlet-title">
      <div class="caption"> <i class="fa fa-star"></i>Delete </div>
    </div>
    <div class="portlet-body">
      <div class="alert alert-block alert-danger fade in">
        <!--<button data-dismiss="alert" class="close" type="button"></button>-->
        <h4 class="alert-heading"><?php echo $this->escapeHtml($title); ?></h4>
        <p> Are you sure that you want to delete this feedback '<?php echo $this->escapeHtml($feedback->comments); ?>'  </p>
		  <p>&nbsp;</p>
			<?php
			$url = $this->url('admin/feedback', array(
				'action' => 'delete',
				'user'     => $this->user,
				'service'     => $this->service,
			));
			?>
        <form action="<?php echo $url; ?>" method="post">
          <div>
            <input type="hidden" name="user" value="<?php echo (int) $feedback->users_id; ?>" />
            <input type="hidden" name="service" value="<?php echo (int) $feedback->service_id; ?>" />
            <input type="submit" name="del" value="Yes" class="btn red" />
            <input type="submit" name="del" value="No" class="btn blue" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
