<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>    
<?php echo $this->headTitle()->prepend('Administrator Login')->setSeparator(' - '); ?>
<?php
    $allMetaTag = (array) $this->headMeta()->getContainer();
    if (empty($allMetaTag)) {
        $this->headMeta()->prependName('keywords', 'Ovessence Login')->appendName('description', 'Ovessence Admistrator Login');
    } else {
        foreach ($allMetaTag as $metaTag) {
            $meta = (array) $metaTag;
            $metaTags[] = $meta['name'];
        }

        if (!in_array('keywords', $metaTags)) {
            $this->headMeta()->prependName('keywords', 'Ovessence Login');
        }

        if (!in_array('description', $metaTags)) {
            $this->headMeta()->appendName('description', 'Ovessence Admistrator Login');
        }
    } 
?>
<meta charset="utf-8" />
<?php echo $this->headMeta(); ?>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/plugins/select2/select2.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/plugins/select2/select2-metronic.css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="<?php echo $this->basePath(); ?>/css/admin/style-metronic.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/style.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/style-responsive.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/plugins.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/pages/login.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath(); ?>/css/admin/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/../img/logo.png')); ?>

<!-- SET BASEURL -->
<script>
var OVEconfig = {
    'BASEURL' : '<?php echo $this->basePath(); ?>'
};
</script> 

</head>
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN LOGO -->
<div class="logo">
	<a href="index.html">
		<!-- <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/logo-big.png" alt=""/> --->
	</a>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">
	<!-- BEGIN LOGIN FORM -->
		<?php echo $this->content; ?>
	<!-- END LOGIN FORM -->
	
	<!-- BEGIN REGISTRATION FORM -->
	
	<!-- END REGISTRATION FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
	<!-- 2014 &copy; Metronic. Admin Dashboard Template. --->
</div>
<!-- END COPYRIGHT -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
	<script src="assets/plugins/respond.min.js"></script>
	<script src="assets/plugins/excanvas.min.js"></script> 
	<![endif]-->
<script src="<?php echo $this->basePath(); ?>/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath(); ?>/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/plugins/select2/select2.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->basePath(); ?>/scripts/core/app.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath(); ?>/scripts/custom/login.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
		jQuery(document).ready(function() {     
		  App.init();
		  Login.init();
		});
	</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
