<?php
	$form->setAttribute('action', $this->url('admin/newsletters',array('action' => 'edit', 'id' => $this->id))); // $this->url('pages', array('action' => 'add'))
	$form->setAttribute('method', 'post');
	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();
	//echo $this->formCollection($form); 
?>

<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption"> <i class="fa fa-reorder"></i> Update Newsletter</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/newsletters/"> <i class="fa fa-list"></i> Newsletters List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-share"></i> Back</a> </div>
    </div>
    <div class="portlet-body form">
		<!-- BEGIN FORM-->
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id'));?>
			<div class="form-body">
				<h3 class="form-section">Newsletter Info</h3>
				<?php if (isset($errors) && count($errors)>0): ?>  
				<div class="alert alert-danger"><button class="close" data-close="alert"></button>
					<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
				</div>
				<?php endif;?>
				<div class="form-group">
					<?php $field = $form->get('subject'); ?>
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?><span class="required">*</span></label>
						<div class="col-md-4">
							<?php echo $this->formInput($field);?>
							<span class="help-block">
								 <?php echo $this->formElementErrors($field); ?>
							</span>
						</div>
					</div>
				</div>
                                <div class="form-group">
					<?php $field = $form->get('user_type_id'); ?>
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?><span class="required">*</span></label>
						<div class="col-md-4">
							<?php echo $this->formSelect($field);?>
							<span class="help-block">
								 <?php echo $this->formElementErrors($field); ?>
							</span>
						</div>
					</div>
				</div>
				<div class="form-group">
					<?php $field = $form->get('message'); ?>
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?><span class="required">*</span></label>
						<div class="col-md-7">
							<?php echo $this->formTextarea($field);?>
							<span class="help-block">
								 <?php echo $this->formElementErrors($field); ?>
							</span>
						</div>
					</div>
				</div>
				<div class="form-group">
					<?php $field = $form->get('send_date'); ?>
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?><span class="required">*</span></label>
						<div class="col-md-9">
							<div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" >
								<?php echo $this->formInput($field);?>
								<span class="input-group-btn">
									<button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
									<span class="help-block">
										<?php echo $this->formElementErrors($field); ?>
									</span>
								</span>
							</div>
						</div>
					</div>
				</div>
				<div class="form-group">
					<?php $field = $form->get('status_id'); ?>
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?><span class="required">*</span></label>
						<div class="col-md-9">
							<?php echo $this->formSelect($field);?>
							<span class="help-block">
								 <?php echo $this->formElementErrors($field); ?>
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="form-actions fluid">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	</div>
</div>
