<?php $status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-outdent"></i>Newsletters List </div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/newsletters', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Newsletter </a> </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/newsletters', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
		<table class="table table-hover table-bordered table-striped">
            <thead>
				<tr>
					<th>Subject</th>
                                        <th>Send To</th>
					<th>Send Date</th>
					<th>Created Date</th>
					<th>Status</th>
					<th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
				</tr>
			</thead>
            <tbody>
			<?php if (isset($newsletters) && count($newsletters)>0) : ?>
				<?php foreach ($newsletters as $newsletter) : ?>
				<tr>
					<td><?php echo $this->escapeHtml($newsletter->subject);?></td>
                                        <td><?php echo $this->escapeHtml($newsletter->user_type);?></td>
					<td><?php echo $this->escapeHtml(date('d-m-Y H:i:s',strtotime($newsletter->send_date)));?></td>
					<td><?php echo $this->escapeHtml(date('d-m-Y H:i:s',strtotime($newsletter->date_created)));?></td>
					<td><span class="label label-sm status label-<?php echo (array_key_exists($newsletter->status_id, $statusArray))?$statusArray[$newsletter->status_id]:'default';?>" id="<?php echo $newsletter->id;?>"><?php echo $this->escapeHtml(ucwords($newsletter->status));?></span>
					</td>
					<td>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/newsletters',array('action'=>'edit', 'id' => $newsletter->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/newsletters',array('action'=>'delete', 'id' => $newsletter->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
						<input class="checkboxes" type="checkbox" value="<?php echo $newsletter->id;?>">
					</td>
				</tr>
				<?php endforeach; ?>
			<?php endif; ?>
			</tbody>
		</table>
		<?php 
		echo $this->paginationControl(
						$newsletters,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/newsletters')  // the route to link to when a user clicks a control link
					);
		?>
		</div>
      </div>
    </div>
  </div>
</div>
