<?php

$title = 'Delete Service'; 
$this->headTitle($title);
?>
<div class="col-md-6">
  <div class="portlet box grey">
    <div class="portlet-title">
      <div class="caption"> <i class="fa fa-user"></i>Delete </div>
    </div>
    <div class="portlet-body">
      <div class="alert alert-block alert-danger fade in">
        <!--<button data-dismiss="alert" class="close" type="button"></button>-->
		<h4 class="alert-heading"><?php echo $this->escapeHtml($title); ?></h4>
		<p> Are you sure that you want to delete this service
          '<?php echo $this->escapeHtml($service->category_name." - ".$service->duration." mins"); ?>' </p>
		  <p>&nbsp;</p>
		<?php
		$url = $this->url('admin/serviceproviderservices', array(
			'action' => 'delete',
			'id'     => $this->id,
			'service_id'     => $this->service_id,
		));
		?>
		<form action="<?php echo $url; ?>" method="post">
          <div>
            <input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
            <input type="hidden" name="service_id" value="<?php echo (int) $service->id; ?>" />
            <input type="submit" name="del" value="Yes" class="btn red" />
            <input type="submit" name="del" value="No" class="btn blue" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
