<?php if ($this->pageCount): ?>

<div class="pagination">
  <ul class="pagination">
    <!-- First page link -->
    <?php if (isset($this->first)  && $this->pageCount != "1" && isset($this->previous)): ?>
    <li> <a href="<?php echo $this->url($this->route); ?>?page=<?php echo (count($this->routeParams) > 0)?$this->first.'&'.http_build_query($this->routeParams):$this->first; ?>"> First </a> </li>
    <?php else: ?>
    <li class="disabled"> <a href="#"> First </a> </li>
    <?php endif; ?>
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <li> <a href="<?php echo $this->url($this->route); ?>?page=<?php echo (count($this->routeParams) > 0)?$this->previous.'&'.http_build_query($this->routeParams):$this->previous; ?>"> << </a> </li>
    <?php else: ?>
    <li class="disabled"> <a href="#"> << </a> </li>
    <?php endif; ?>
    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
    <li> <a href="<?php echo $this->url($this->route);?>?page=<?php echo (count($this->routeParams) > 0)?$page.'&'.http_build_query($this->routeParams):$page;; ?>"> <?php echo $page; ?> </a> </li>
    <?php else: ?>
    <li class="active"> <a href="#"><?php echo $page; ?></a> </li>
    <?php endif; ?>
    <?php endforeach; ?>
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <li> <a href="<?php echo $this->url($this->route); ?>?page=<?php echo (count($this->routeParams) > 0)?$this->next.'&'.http_build_query($this->routeParams):$this->next;; ?>"> >> </a> </li>
    <?php else: ?>
    <li class="disabled"> <a href="#"> >> </a> </li>
    <?php endif; ?>
    <!-- Last page link -->
    <?php if (isset($this->last)  && $this->pageCount != "1" && isset($this->next)): ?>
    <li> <a href="<?php echo $this->url($this->route); ?>?page=<?php echo (count($this->routeParams) > 0)?$this->last.'&'.http_build_query($this->routeParams):$this->last; ?>"> Last </a> </li>
    <?php else: ?>
    <li class="disabled"> <a href="#"> Last </a> </li>
    <?php endif; ?>
  </ul>
</div>
<?php endif; ?>
