<?php 

$title = 'Edit Site Action';
$this->headTitle($title);

$form = $this->form; 
$form->setAttribute('action', $this->url(
    'admin/siteactions',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/siteactions"> <i class="fa fa-pencil"></i>Site Action List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
	  <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<h3 class="form-section">Site Action Info</h3>
			<div class="row">
				<?php $action_meta = $form->get('action_meta'); ?>
				<div class="form-group <?php echo ($this->formElementErrors($action_meta) != "")?"has-error":"";?>">   
					<label class="control-label col-md-2"><?php echo $this->formLabel($action_meta); ?></label>
					<div class="col-md-10">
						<?php echo $this->formSelect($action_meta);?>
						<span class="help-block">
							 <?php echo strip_tags($this->formElementErrors($action_meta));?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $controller_name = $form->get('controller_name'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($controller_name) != "")?"has-error":"";?>">
					<label class="control-label col-md-2"><?php echo $this->formLabel($controller_name); ?></label>
					<div class="col-md-10">
						<?php echo $this->formInput($controller_name); ?>	
						<span class="help-block">
							 <?php echo strip_tags($this->formElementErrors($controller_name)); ?>
						</span>
					</div>
				</div>
			</div>
			<div class="row">
				<?php $action_name = $form->get('action_name'); ?>		
				<div class="form-group  <?php echo ($this->formElementErrors($action_name) != "")?"has-error":"";?>">
					<label class="control-label col-md-2"><?php echo $this->formLabel($action_name); ?></label>
					<div class="col-md-10">
						<?php echo $this->formInput($action_name); ?>	
						<span class="help-block">
							 <?php echo strip_tags($this->formElementErrors($action_name)); ?>
						</span>
					</div>
				</div>
			</div>
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
	</div>
</div>
