<?php
$title = 'View Message';
$this->headTitle($title);
?>
<?php if(isset($replyMessage) && !empty($replyMessage)) { ?>
	<div class="note note-success">
		<p><?php echo $replyMessage; ?></p>	
	</div>	
<?php }?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/messages/inbox"> <i class="fa fa-pencil"></i>Inbox</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
    <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<div class="form-body">
			Subject: <h3 class="form-section"><?php echo isset($master_message->subject) ? $master_message->subject : '' ; ?></h3>
		<?php if(isset($replies) && count($replies) > 0) { ?>
			<?php foreach($replies as $reply) { ?>
				<div class="row">
					<div class="form-group">
						<label class="control-label col-md-1">From:</label>
						<div class="col-md-11">
							<span class="help-block">
								<?php echo $reply->from_name; ?>&nbsp;&nbsp;&nbsp;(<?php echo $reply->created_date; ?>)	
							</span>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-1">Message:</label>
						<div class="col-md-8">
							<span class="help-block">
								<?php echo $reply->message; ?>
							</span>
						</div>
						<?php if($reply->from_user_id!=$current_user_id){ // current user id ?>
						<div class="col-md-3">
							<button type="" class="btn default" onclick="$( '#replytoggle<?php echo $reply->id; ?>' ).toggle();">Reply</button>
						</div>
						<?php } ?>
					</div>
				</div>
				<div class="row">&nbsp;</div>
				<?php if($reply->from_user_id!=$current_user_id){ // current user id ?>
				<form id="messageForm<?php echo $reply->id; ?>" name="messageForm<?php echo $reply->id; ?>" method="post" action="<?php echo $this->basePath(); ?>/admin/messages/view/<?php echo $reply->id; ?>">
				<div class="row" id="replytoggle<?php echo $reply->id; ?>" style="<?php echo (($msg_error) != "") ? "display:block" : "display:none" ;?> ">
					<div class="form-group  <?php echo (($msg_error) != "")?"has-error":"";?>">
						<label class="control-label col-md-1">Reply Message</label>
						<div class="col-md-11">
							<textarea  id="ReplyMessage<?php echo $reply->id; ?>" name="ReplyMessage<?php echo $reply->id ?>" rows="10" cols="50" class="form-control"></textarea>
							<span class="help-block">
								<?php echo (($msg_error) != "") ? $msg_error : ""; ?>
							</span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-offset-1 col-md-12">
							<button type="submit" class="btn">Submit</button>
						</div>
					</div>
					<input type="hidden"  id="subject" name="subject<?php echo $reply->id; ?>" value="<?php echo $reply->subject; ?>">
					<input type="hidden"  id="replyId" name="replyId" value="<?php echo $reply->id; ?>">
					<input type="hidden"  id="topLevel_id" name="topLevel_id<?php echo $reply->id; ?>" value="<?php echo $reply->topLevel_id; ?>">
					<input type="hidden"  id="toUserID" name="toUserID<?php echo $reply->id; ?>" value="<?php echo $reply->from_user_id; ?>">                            
				</div>
				</form>
				<?php } ?>
			
			<?php } ?>
                     </div>
		<?php } ?>
	  </div>
	</div>
</div>
