<?php
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-desktop"></i>Advertisements List </div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/advertisement', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Advertisement </a></div>
        <!--<div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/advertisement', array('action'=>'changestatus'));?>' ><i class="fa fa-check"></i>Apply</button>
		</div>-->
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
              <thead>
                  <tr>
                      <th>Banner Name</th>
                      <th>Banner Size</th>
                      <!--<th>Status</th>-->
                      <th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
                  </tr>
              </thead>
            <tbody>
              <?php if (isset($advertisements) && count($advertisements)>0) : ?>
              <?php foreach ($advertisements as $advertisement) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($advertisement->banner_name);?></td>
                <td><?php echo $this->escapeHtml($advertisement->banner_width.'x'.$advertisement->banner_height.' px');?></td>
                <!--<td><span class="label label-sm status label-<?php  echo (array_key_exists($advertisement->status_id, $statusArray))?$statusArray[$advertisement->status_id]:'default';?>" id="<?php echo $advertisement->id;?>"><?php echo $this->escapeHtml(ucwords($advertisement->status));?></span></td>-->
                <td>
                    <a class="btn default btn-xs default" href="<?php echo $this->url('admin/advertisement', array('action' => 'edit', 'id' => $advertisement->id)); ?>"><i class="fa fa-edit" title="edit" ></i></a>
                    <a class="btn default btn-xs default" href="<?php echo $this->url('admin/advertisement', array('action' => 'delete', 'id' => $advertisement->id)); ?>"><i class="fa fa-trash-o" title="delete" ></i></a>
                    <!--<input class="checkboxes" type="checkbox" value="<?php echo $advertisement->id; ?>">-->
                </td>
              </tr>
              <?php endforeach; ?>
              <?php endif; ?>
            </tbody>
          </table>
          <?php 
          echo $this->paginationControl(
                  $advertisements, // the paginator object
                  'sliding', // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                  array('partial/paginator.phtml', 'Admin'), // the partial to use to render the control
                  array('route' => 'admin/advertisement')  // the route to link to when a user clicks a control link
               );
          ?>
        </div>
      </div>
    </div>
  </div>
</div>