<?php
$status = (isset($status) && count($status) > 0) ? $status->toArray() : array(); 
$statusArray = array('1' => 'success', '2' => 'warning');
?>
<div class="row">
    <div class="col-md-12 col-sm-12">

        <?php if (isset($successMsgs) && count($successMsgs) > 0): ?>
            <div class="note note-success">
                <?php
                foreach ($successMsgs as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <?php if (isset($errors) && count($errors) > 0): ?>
            <div class="note note-danger">
                <?php
                foreach ($errors as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <div class="note" id="error" style="display:none;"></div>

        <div class="portlet grey box">
            <div class="portlet-title">
                <div class="caption"> <i class="fa fa-file-text"></i>Faq Index List</div>
                <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/faqindex', array('action' => 'add')); ?>"> <i class="fa fa-pencil"></i> Add New Faq Index </a> </div>
                <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
                    <?php
                    if (isset($status) && count($status) > 0) {
                        echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
                        foreach ($status as $value) {
                            echo '<option value="' . $value['status_id'] . '" >' . ucwords($value['status']) . '</option>';
                        }
                        echo '</select>';
                    }
                    ?>
                    <button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/faqindex', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Index Name</th>
                                <th>Display Order</th>
                                <th>Status</th>
                                <th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($faqindex) && count($faqindex) > 0) : ?>
                                <?php foreach ($faqindex as $index) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($index->index_name); ?></td>
                                        <td><?php echo $this->escapeHtml($index->order_by); ?></td>
                                        <td><span class="status label label-sm label-<?php echo (array_key_exists($index->status_id, $statusArray)) ? $statusArray[$index->status_id] : 'default'; ?>" id="<?php echo $index->id; ?>"><?php echo $this->escapeHtml(ucwords($index->status)); ?></span></td>
                                        <td>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/faqindex', array('action' => 'edit', 'id' => $index->id)); ?>"><i class="fa fa-edit" title="edit" ></i></a>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/faqindex', array('action' => 'delete', 'id' => $index->id)); ?>"><i class="fa fa-trash-o" title="delete" ></i></a>
                                            <input class="checkboxes" type="checkbox" value="<?php echo $index->id; ?>">
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php
                    echo
                    $this->paginationControl(
                            $faqindex, 'sliding', array('partial/paginator.phtml', 'Admin'), array('route' => 'admin/faqindex')
                    );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
