<?php
$form->setAttribute('action', '/admin/states/');
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'states_filter');
$form->prepare();
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gear"></i>States List </div>
        <div class="actions"> <!--<a class="btn default btn-sm" href="<?php echo $this->url('admin/states', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New State </a>--></div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/states', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped" id="states_table" data-path='<?php echo $this->url('admin/states');?>'>
            <thead>
				<tr>
					<th>#</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'state_name') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='state_name'>State Name</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'country') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='country'>Country</th>
					<th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'status') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='status'>Status</th>
					<th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
				</tr>
				<tr class="filter" role="row">
					<?php  echo $this->form()->openTag($form); ?>
					<td rowspan="1" colspan="1">
						<!--<?php  echo $this->formInput($form->get('state_code')); ?>-->
					</td>
					<td rowspan="1" colspan="1">
						<?php  echo $this->formInput($form->get('state_name')); ?>
					</td>
					<td rowspan="1" colspan="1">
						<?php  echo $this->formSelect($form->get('country_id')); ?>
					</td>
					<td rowspan="1" colspan="1">
						<?php  echo $this->formSelect($form->get('status_id')); ?>
					</td>
					<td rowspan="1" colspan="1">
						<button class="btn btn-sm default filter-submit margin-bottom search" data-form="states_filter" data-tbl="states_table" data-path='<?php echo $this->url('admin/states');?>'><i class="fa fa-search"></i> Search</button>
						<!--<button class="btn btn-sm red filter-cancel" type="reset"><i class="fa fa-times"></i> Reset</button>-->
					</td>
					<?php  echo $this->form()->closeTag();?>
				</tr>
            </thead>
            <tbody>
              <?php if (isset($states) && count($states)>0) : ?>
              <?php foreach ($states as $state) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($state->id);?></td>
                <td><?php echo $this->escapeHtml($state->state_name);?></td>
                <td><?php echo $this->escapeHtml($state->country_name);?></td>
                <td><span class="label label-sm status label-<?php  echo (array_key_exists($state->status_id, $statusArray))?$statusArray[$state->status_id]:'default';?>" id="<?php echo $state->id;?>"><?php echo $this->escapeHtml(ucwords($state->status));?></span></td>
                <td>
					<!--<a class="btn default btn-xs blue" href="<?php echo $this->url('admin/states',array('action'=>'edit', 'id' => $state->id));?>"><i class="fa fa-edit"></i> Edit</a>
					<a class="btn default btn-xs red" href="<?php echo $this->url('admin/states',array('action'=>'delete', 'id' => $state->id));?>"><i class="fa fa-trash-o"></i> Delete</a>-->
					<input class="checkboxes" type="checkbox" value="<?php echo $state->id;?>">
              </tr>
              <?php endforeach; ?>
              <?php endif; ?>
            </tbody>
          </table>
          <?php 
		echo $this->paginationControl(
						$states,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/states', 'routeParams' => $this->postedData)  // the route to link to when a user clicks a control link
					);
?>
        </div>
      </div>
    </div>
  </div>
</div>
