<?php
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'horizontal');
$form->prepare();

//echo $this->formCollection($form); 
?> 

<!-- CONTENT START HERE -->
<div id="content">
    <div id="banner">
        <?php if (isset($banners) && is_array($banners) && count($banners) > 0):?>
        <img src="<?php echo isset($banners[0]['banner_url'])?$banners[0]['banner_url']:'';?>" alt="" />
        <?php endif;?>
    </div>
    <div class="main">
        <ul id="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                Verification 
            </li>
        </ul>
        <article class="section-block">
            <h2>
                verification 
                <span>
                    <small>
                        Essence of an Idea
                    </small>
                </span>
            </h2>						
            <div class="verification-form">
                <div id ="msg" ></div>

                <?php echo $this->form()->openTag($form); ?>
                <?php $field = $form->get('verification_type'); ?>
                <?php echo $this->formRadio($field); ?>
                <?php echo strip_tags($this->formElementErrors($field)); ?>
                <div id="from_container" ></div>	
                <?php echo $this->form()->closeTag(); ?>
            </div>

        </article>

    </div>
</div>
<!-- CONTENT END HERE -->


<!-- CONTENT START HERE 
                        <div id="content">
                                <div id="banner">
                                        <img src="<?php /* echo $this->basePath(); ?>/img/about-banner.jpg" alt="">
                  </div>
                  <div class="main">
                  <ul id="breadcrumb">
                  <li>
                  <a href="#">Home</a>
                  </li>
                  <li>
                  Verification
                  </li>
                  </ul>
                  <article class="section-block">
                  <h2>
                  verification
                  <span>
                  <small>
                  Essence of an Idea
                  </small>
                  </span>
                  </h2>

                  <div class="verification-form">
                  <div class="hide-div" id="response" > <?php if($flag==3){ ?> <label id='msg'></label> <?php } ?></div>

                  <?php echo $this->form()->openTag($form);?>
                  <?php $field = $form->get('verification_type'); ?>
                  <?php echo $this->formRadio($field);?>
                  <?php echo strip_tags($this->formElementErrors($field));?>
                  <div id="from_container" class="hide-div">
                  <div id="email_container" class="hide-div">
                  <?php if($flag==3){ ?>
                  <div class="email-verification"  id="linkverification">
                  <?php $field = $form->get('emailid'); ?>
                  <?php echo $this->formInput($field);?>
                  <?php echo strip_tags($this->formElementErrors($field));?>

                  <input type="submit" class="black sendlink" value="Send me link" />
                  </div>
                  <?php } ?>
                  </div>

                  <div id="number_container" class="hide-div">
                  <?php if($noflag==3){ ?>
                  <div class="email-verification"  id="numberverification">
                  <?php $field = $form->get('mobile_no'); ?>
                  <?php echo $this->formInput($field);?>
                  <?php echo strip_tags($this->formElementErrors($field));?>
                  <input type="submit" class="black sendcode" value="Send Me code" />
                  </div>
                  <?php } ?>
                  </div>
                  <?php if($flag==1 || $noflag==1){ ?>
                  <div class="email-verification"  id="verifycode">

                  <?php $field = $form->get('verifycodeval'); ?>
                  <?php echo $this->formInput($field);?>
                  <?php echo strip_tags($this->formElementErrors($field));?>
                  <input type="submit" class="black verifycode" value="verifiy" />
                  </div>
                  <?php } ?>
                  </div>
                  <?php  echo $this->form()->closeTag(); */ ?>
                                                </div>
                                                
                                        </article>
                                        
                                </div>
                                
                        </div>
                        CONTENT END HERE -->


<!--
<div class="portlet box grey">
        <div class="portlet-title">
                <div class="caption"> <i class="fa fa-reorder"></i> Verification page</div>
        
    </div>
    <div class="portlet-body form">
                <div class="form-body">
<?php /* if (isset($errors) && count($errors)>0): ?>  
  <div class="alert alert-danger"><button class="close" data-close="alert"></button>
  <?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
  </div>
  <?php endif;?>

  <?php echo $this->form()->openTag($form);?>
  <li>
  <?php $field = $form->get('mobile_no'); ?>
  <?php echo $this->formInput($field);?>
  <?php echo strip_tags($this->formElementErrors($field));?>
  </li>
  <li>
  <?php $field = $form->get('verification_type'); ?>
  <?php echo $this->formRadio($field);?>
  <?php echo strip_tags($this->formElementErrors($field));?>
  </li>
  <li class="input-button">

  <?php echo $this->formSubmit($form->get('submit')); ?>
  </li>
  <?php  echo $this->form()->closeTag(); */ ?>
                        
                </div>
        </div>
</div> -->


