<?php
$title = 'Add New Module';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/sitemodules', array('action' => 'add'))); 
$form->prepare();

?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/sitemodules"> <i class="fa fa-pencil"></i>Site Module List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
    <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<h3 class="form-section">Module Info</h3>
			<div class="row">
				<div class="col-md-6">
					<?php $module_name = $form->get('module_name'); ?>		
					<div class="form-group  <?php echo ($this->formElementErrors($module_name) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($module_name); ?></label>
						<div class="col-md-9">
							<?php echo $this->formInput($module_name); ?>	
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($module_name)); ?>
							</span>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<label class="col-md-2 control-label flagLabel">Set Flag</label> 
					<div class="col-md-10">
						<div class="checkbox-list">
							
							<?php $frontFlag = $form->get('frontFlag'); ?>		
							<label class="checkbox-inline <?php echo ($this->formElementErrors($frontFlag) != "")?"has-error":"";?>">
								<div class="checker">
									<span><?php echo $this->formCheckbox($frontFlag); ?></span>
								</div> 
								<?php echo $this->formLabel($frontFlag); ?> 
							</label>	
							
							<?php $adminFlag = $form->get('adminFlag'); ?>
							<label class="checkbox-inline <?php echo ($this->formElementErrors($adminFlag) != "")?"has-error":"";?>">
								<div class="checker" id="uniform-inlineCheckbox22">
									<span><?php echo $this->formCheckbox($adminFlag); ?></span>
								</div>
								<?php echo $this->formLabel($adminFlag); ?>
							</label>
							<span class="help-block" style="color: #B94A48;">
								 <?php echo strip_tags($this->formElementErrors($frontFlag)); ?>
							</span>
						</div>
					</div>
				</div>
			</div>
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
	</div>
</div>
