<div class="row">
  <div class="col-md-12 col-sm-12">
	  
	<?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?> 
		</div>
	<?php endif;?>
	<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
	<?php endif;?>
	<div class="note" id="error" style="display:none;"></div>
	
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gear"></i>Site Modules List</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/sitemodules', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Module </a> </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>Module Name</th>
				<th>Action</th>
              </tr>
            </thead>
            <tbody>
             <?php if (isset($modules) && count($modules)>0) : ?>
             <?php foreach ($modules as $module) : ?>
              <tr>
					<td><?php echo $this->escapeHtml($module->module_name);?></td>
					<td>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/sitemodules',array('controller'=>'sitemodules','action'=>'edit', 'id' => $module->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
						<!--<a class="btn default btn-xs" href="<?php echo $this->url('admin/sitemodules',array('controller'=>'sitemodules','action'=>'delete', 'id' => $module->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>-->
					</td>
				</tr>
				<?php endforeach; ?>
			<?php endif; ?>
            </tbody>
          </table>
          <?php 
			echo 
			$this->paginationControl(
					$modules,  
					'sliding',   
					array('partial/paginator.phtml', 'Admin'),  
					array('route' => 'admin/sitemodules')  
				);
			?>
        </div>
      </div>
    </div>
  </div>
</div>
