<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/media', array('action' => 'edit', 'id' => $this->id)));
	$form->prepare(); 
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> Add Media </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/media/"> <i class="fa fa-list"></i> Media List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
    <div class="form-body">
	    <!--PAGE CONTENT BEGINS-->
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php if (isset($file_errors) && count($file_errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($file_errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($msg))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<div class="row">
				<div class="col-md-6">
					<?php $field = $form->get('user_id'); ?>
					<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
						<div class="col-md-9">
							<?php echo $this->formSelect($field);?>
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($field));?>
							</span>
						</div>
					</div>
				</div>
				<!--/span-->
				<div class="col-md-6">
					<?php $field = $form->get('media_title'); ?>
					<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">   <!-- has-error class to make error div highlighted -->
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
						<div class="col-md-9">
							<?php echo $this->formInput($field);?>
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($field));?>
							</span>
						</div>
					</div>
				</div>
				<!--/span-->
			</div>
			<!--/row-->
			
			<div class="row">
				<div class="col-md-6">
					<?php $field = $form->get('media_type'); ?>		
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo strip_tags($this->formLabel($field)); ?></label>
						<div class="col-md-9">
							<?php echo $this->formRadio($field); ?>	
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($field)); ?>
							</span>
						</div>
					</div>
				</div>
				
				<div class="col-md-6">
					<?php $field = $form->get('media_url')->setAttributes(array('class' => '')); ?>		
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
						<div class="col-md-9">
							<div class="fileinput fileinput-new" data-provides="fileinput">
								<span class="btn default btn-file">
									<span class="fileinput-new">
										 Select file
									</span>
									<span class="fileinput-exists">
										 Change
									</span>
									<?php echo $this->formFile($field);?>
								</span>
								<span class="fileinput-filename">
								</span>
								 &nbsp;
								<a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">
								</a>
								<?php if ($media->media_type == '1') {
											echo '&nbsp;&nbsp;<img src="'.str_replace('Media','Media_thumb',$media->media_url).'" height="50" width="50" />';
										} else {
											//echo '<iframe style="margin-bottom:-17px" id="player_1" src="http://player.vimeo.com/video/'.$media->media_url.'?api=1&amp;player_id=player_1" width="50" height="50" frameborder="0"></iframe>';
										}
								?>
							</div>
						</div>
					</div>	
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-6">
					<?php $field = $form->get('media_description'); ?>		
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
						<div class="col-md-9">
							<?php echo $this->formTextarea($field); ?>	
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($field)); ?>
							</span>
						</div>
					</div>
				</div>
				
				<div class="col-md-6">
					<?php $field = $form->get('status_id'); ?>		
					<div class="form-group  <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
						<div class="col-md-9">
							<?php echo $this->formSelect($field); ?>	
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($field)); ?>
							</span>
						</div>
					</div>
				</div>
			</div>
			
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
	</div>
</div>
