<?php
$title = 'Delete Subscription Duration';
$this->headTitle($title);
?>

<div class="col-md-6">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption"> <i class="fa fa-random"></i>Delete </div>
        </div>
        <div class="portlet-body">
            <div class="alert alert-block alert-danger fade in">
                <!--<button data-dismiss="alert" class="close" type="button"></button>-->
                <h4 class="alert-heading"><?php echo $this->escapeHtml($title); ?></h4>
                <p> Are you sure that you want to delete this subscription duration '<?php echo $this->escapeHtml($subscriptionduration->duration . " " . $subscriptionduration->durationin . "@" . $subscriptionduration->price); ?>' </p>
                <p>&nbsp;</p>
                <?php
                $url = $this->url('admin/subscriptiondurations', array(
                    'action' => 'delete',
                    'subscription_id' => $this->subscription_id,
                    'id' => $this->id,
                ));
                ?>
                <form action="<?php echo $url; ?>" method="post">
                    <div>
                        <input type="hidden" name="id" value="<?php echo (int) $subscriptionduration->id; ?>" />
                        <input type="submit" name="del" value="Yes" class="btn red" />
                        <input type="submit" name="del" value="No" class="btn blue" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
