<!--
 @auther <badelalk@clavax.us>
-->
<!-- CONTENT START HERE -->
<div id="content">
    <a href="javascript:;" id="login-a" class="none-display"></a>
    <a class="none-display" href="javascript:;" id="register-a"></a>
    <div class="login-option slide-wrapper">
        <div class="form-main login-section">
            <h2>Login / Login with -</h2>
            <!--<span>tempor incididunt ut labore et dolore magna aliqua. </span>-->
            <ul class="social-link">
                <li class="facebook">
					
                    <a href="<?php  echo $this->basePath();?>/facebooklogin">
                        <i></i>Facebook
                    </a>
                </li>
                <li class="linkedin">
                    <a href="<?php echo $this->basePath();?>/linkedinlogin">
                    
                        <i></i>LinkedIn
                    </a>
                </li>
                <li class="g-plus">
                    <a href="<?php echo $this->basePath();?>/googlelogin">
                        <i></i>Google Plus
                    </a>
                </li>
            </ul>
        </div>
        <div class="form-main register-section">
            <h2>Register / Register with -</h2>
            <!--<span>tempor incididunt ut labore et dolore magna aliqua. </span>-->
            <ul class="social-link">
                <li class="facebook">
                    <a href="#">
                        <i></i>Facebook
                    </a>
                </li>
                <li class="linkedin">
                    <a href="#">
                        <i></i>LinkedIn
                    </a>
                </li>
                <li class="g-plus">
                    <a href="#">
                        <i></i>Google Plus
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="form-wrapper slide-wrapper <?php if (isset($errors) && count($errors)>0): ?>registerError-resize <?php endif;?>">
        <div class="form-main  login-section">
            <?php 
            $form = $this->form;
            
            //var_dump($form->getName()); die;
            
            $form->setAttribute('action', $this->url('login', array('action' => 'index'))); 
            $form->setAttribute('id', 'User'); 
            $form->setAttribute('name','User'); 
            $form->prepare();
            echo $this->form()->openTag($form);
            //var_dump($form); die;
            ?>
                 
                <div class="page-form">
                    <span class="icon-image"></span>
                    <!--<dfn>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua 456.
                    </dfn>-->
                    <?php if(!empty($loginError)) {
                        echo "<div class='error-msg'><label>".$loginError."</label></div>";
                    } ?>
                    
                    <ul>
                        <li>
                            <?php $field = $form->get('user_type_id'); ?>
                            <span class="myself"> I am a </span>                            
                            <?php echo $this->formSelect($field); ?>
                           
                        </li>
                        <li>
                            <?php $field = $form->get('user_name'); ?>
                            <?php echo $this->formInput($field);?>
                           
                        </li>
                        <li>
                            <?php $field = $form->get('Pass'); ?>
                            <?php echo $this->formInput($field);?>
                           
                        </li>
                        <li class="align-left check">
                            <label for="remember-me">
                                <?php $field = $form->get('rememberme'); ?>
                                <?php echo $this->formCheckbox($field);?>
                                <span></span> Remember me
                            </label>
                        </li>
                        <li class="input-button">
                            <?php echo $this->formSubmit($form->get('submit')); ?>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/forgetpassword">Forgot password?</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/forgetusername">Forgot username?</a>
                        </li>
                    </ul>
                </div>
                <div class="register-btn" id="login-btn">
                    <span>Not a member yet?</span>
                    <a href="#register-a" class="green-btn">Register Now!</a>
                </div>
            
            <?php echo $this->form()->closeTag(); ?>
        </div>
        
        
			
        <div class="form-main register-section">
			
            <?php 
            $register_form = $this->register_form;
            
            //var_dump($form->getName()); die;
            
            $register_form->setAttribute('action', $this->url('register', array('action' => 'index')).'#register-a'); 
            $register_form->setAttribute('id', 'Register'); 
            $register_form->setAttribute('name','Register'); 
            $register_form->prepare();
            //echo $this->form()->openTag($form);
            //var_dump($form); die;
            ?>
            <?php echo $this->form()->openTag($register_form); ?>
            <!-- <form action="/register/index#register-a" method="post" name="Register" id="Register">  --->
            <div class="page-form">
                <span class="icon-image"></span>
                <!--<dfn>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua 123.
                </dfn>-->
              
                <?php if (isset($errors) && count($errors) > 0): ?>  
                    <div class="error-msg">
                        <?php foreach ($errors as $field => $msg) {
                            echo '<label>' . ucfirst(strtolower(strip_tags(end($msg)))) . '</label>';
                        } ?>
                    </div>
                <?php endif; ?>
              
                <?php if(!empty($loginError)) {
                        echo "<div class='error-msg'><label>".$loginError."</label></div>";
                    }
                     ?>
                <?php 
                //var_dump($this->formElementErrors());// die;
                //$errorsMessages =$this->register_form->getMessages();
                //echo '<pre>';
                //print_r($errorsMessages);
                //die;
                ?>
                <ul>
                    <li>
                        <?php $field = $register_form->get('user_type_id'); ?>
                        <span class="myself"> I am a </span>                            
                        <?php echo $this->formSelect($field); ?>
                        <?php //echo strip_tags($this->formElementErrors($field));?>
                    </li>
                    <li>
                        <?php $field = (isset($fb_login->first_name) && !empty($fb_login->first_name))?$register_form->get('first_name')->setValue($fb_login->first_name):$register_form->get('first_name'); ?>
                        <?php // if(isset($fb_login->first_name)){  echo $this->formInput($field).value($fb_login->first_name); }  ?>
                        <?php echo $this->formInput($field); ?>
                        
                    </li>
                    <li>
                        <?php $field = (isset($fb_login->last_name) && !empty($fb_login->last_name))?$register_form->get('last_name')->setValue($fb_login->last_name):$register_form->get('last_name'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li>
                        <?php $field = (isset($fb_login->user_name) && !empty($fb_login->user_name))?$register_form->get('user_name')->setValue($fb_login->user_name):$register_form->get('user_name'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li>
                        <?php $field = (isset($fb_login->email) && !empty($fb_login->email))?$register_form->get('email')->setValue($fb_login->email):$register_form->get('email'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li>
                        <?php $field = (isset($fb_login->email) && !empty($fb_login->email))?$register_form->get('confirm_email')->setValue($fb_login->email):$register_form->get('confirm_email'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li>
                        <?php $field = $register_form->get('Pass'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li>
                        <?php $field = $register_form->get('confirm_password'); ?>
                        <?php echo $this->formInput($field);?>
                        
                    </li>
                    <li class="input-button">
                        <?php echo $this->formSubmit($register_form->get('register_submit')); ?>
                    </li>
                </ul>
            </div>
            <div class="register-btn">
                <span>Already a member?</span>
                <a href="#login-a" class="green-btn">Login Now!</a>
            </div>
            <?php //echo $this->form()->closeTag(); ?>
            </form>
        </div>
    </div>
</div>
<!-- CONTENT END HERE -->
