<?php
$status = (isset($status) && count($status) > 0) ? $status->toArray() : array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <?php if (isset($successMsgs) && count($successMsgs) > 0): ?>
            <div class="note note-success">
                <?php foreach ($successMsgs as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                } ?>
            </div>
            <?php endif; ?>
            <?php if (isset($errors) && count($errors) > 0): ?>
            <div class="note note-danger">
            <?php foreach ($errors as $msg) {
                echo '<p> ' . $msg . ' </p>';
            } ?>
            </div>
<?php endif; ?>
        <div class="note" id="error" style="display:none;"></div>
        <div class="portlet grey box">
            <div class="portlet-title">
                <div class="caption"> <i class="fa fa-random"></i>Subscription Features </div>
                <div class="actions"> 
                    <!-- action button will be here -->                    
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th> Feature Name </th>
                                <th> Description </th>
                                <th> Status </th>
                                <th width="230" >Action </th>
                            </tr>
                        </thead>
                        <tbody>
                    <?php if (isset($features) && count($features) > 0) : ?>
                        <?php foreach ($features as $feature) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($feature->feature_name); ?> </td>
                                        <td><?php echo $this->escapeHtml($feature->description); ?> </td>
                                        <td><span class="label label-sm label-<?php echo (array_key_exists($feature->status_id, $statusArray)) ? $statusArray[$feature->status_id] : 'default'; ?>" id="<?php echo $feature->id; ?>"><?php echo $this->escapeHtml(ucwords($feature->status)); ?></span></td>
                                        <td>
                                            <a class="btn default btn-xs default" href="<?php echo $this->url('admin/subscriptionfeatures', array('action' => 'edit','id' => $feature->id)); ?>"><i class="fa fa-edit" title="Edit"></i></a>
                                        </td>
                                    </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                        </tbody>
                    </table>
                    <?php
                    echo $this->paginationControl(
                            $features, // the paginator object
                            'sliding', // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                            array('partial/paginator.phtml', 'Admin'), // the partial to use to render the control
                            array('route' => 'admin/subscriptionfeatures')  // the route to link to when a user clicks a control link
                    );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
