<?php
	$form->setAttribute('action', '');
	$form->setAttribute('method', 'post');
	$form->setAttribute('id', 'userFilter');
	$status = (isset($status) && count($status)>0)?$status->toArray():array();
	$statusArray = array('9' => 'success', '5' => 'warning', '10' => 'danger', '3' => 'danger');
	$settingArray = array('1' => 'success', '0' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  
	 <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
	<?php endif;?>
	<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
	<?php endif;?>
	<div class="note" id="error" style="display:none;"></div>
	
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-user"></i>Users List </div>
        <div class="actions">
			<a class="btn default btn-sm" href="<?php echo (count($this->postedData) > 0)?$this->url('admin/users', array('action'=>'export')).'?'.http_build_query($this->postedData):$this->url('admin/users', array('action'=>'export'));?>"> <i class="fa fa-download"></i> Export </a>  
			<a class="btn default btn-sm" href="<?php echo $this->url('admin/users', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New User </a> 
        </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				/*echo '<option value="enablechat" >Enable Chat</option>
					  <option value="disablechat" >Disable Chat</option>
					  <option value="enablesms" >Enable Sms</option>
					  <option value="disablesms" >Disable Sms</option>
					  <option value="enableemail" >Enable Email</option>
					  <option value="disableemail" >Disable Email</option>
					  </select>';*/
					  echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/users', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped" id="users_table" data-path='<?php echo $this->url('admin/users');?>'>
              <thead>
                  <tr>
                      <th>Name</th>
                      <th>Avtar</th>
                      <th>Username</th>
                      <th>User Type</th>
                      <th>Email</th>
                      <th width='148'>Created On</th>
                      <th width='148'>Last Login</th>
                      <!--<th>Chat</th>
                      <th>Sms</th>
                      <th>Email</th>-->
                      <th>Status</th>
                      <th width="162" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
                  </tr>
                  <tr class="filter" role="row">
                      <?php echo $this->form()->openTag($form); ?>
                      <td rowspan="1" colspan="1">
                          <?php echo $this->formInput($form->get('name')); ?>
                      </td>
                      <td rowspan="1" colspan="1">
                          &nbsp;
                      </td>
                      <td rowspan="1" colspan="1">
                          <?php echo $this->formInput($form->get('user_name')); ?>
                      </td>
                      <td rowspan="1" colspan="1">
                          <?php echo $this->formSelect($form->get('user_type_id')); ?>
                      </td>
                      <td rowspan="1" colspan="1">
                          <?php echo $this->formInput($form->get('email')); ?>
                      </td>
                      <td rowspan="1" colspan="1" width='148'>
                          <div class="input-group date date-picker margin-bottom-5" data-date-format="dd-mm-yyyy">
                              <?php echo $this->formInput($form->get('from')); ?>
                              <span class="input-group-btn">
                                  <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                              </span>
                          </div>
                          <div class="input-group date date-picker" data-date-format="dd-mm-yyyy">
                              <?php echo $this->formInput($form->get('to')); ?>
                              <span class="input-group-btn">
                                  <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                              </span>
                          </div>
                      </td>
                      <td rowspan="1" colspan="1" width='148'>
                          <div class="input-group date date-picker margin-bottom-5" data-date-format="dd-mm-yyyy">
                              <?php echo $this->formInput($form->get('from_login')); ?>
                              <span class="input-group-btn">
                                  <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                              </span>
                          </div>
                          <div class="input-group date date-picker" data-date-format="dd-mm-yyyy">
                              <?php echo $this->formInput($form->get('to_login')); ?>
                              <span class="input-group-btn">
                                  <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                              </span>
                          </div>
                      </td>
                      <!--<td rowspan="1" colspan="1">
                      <?php //echo $this->formSelect($form->get('chat')); ?>
                      </td>
                      <td rowspan="1" colspan="1">
                      <?php //echo $this->formSelect($form->get('sms')); ?>
                      </td>
                      <td rowspan="1" colspan="1">
                      <?php // echo $this->formSelect($form->get('email_status')); ?>
                      </td>-->
                      <td rowspan="1" colspan="1">
                          <?php echo $this->formSelect($form->get('status_id')); ?>
                      </td>
                      <td rowspan="1" colspan="1" width="162">
                          <button style='margin-bottom:4px' class="btn btn-sm default filter-submit margin-bottom search" data-form="userFilter" data-tbl="users_table" data-path='<?php echo $this->url('admin/users'); ?>'><i class="fa fa-search"></i> Search</button>
                          <button class="btn btn-sm default filter-cancel" type="reset" onclick="$('input, select').val(''); $('.select2').select2('val', '');"><i class="fa fa-times"></i> Reset</button>
                      </td>
                  </tr>
                  <?php echo $this->form()->closeTag(); ?>
              </thead>
            <tbody>
             <?php if (isset($users)) { ?>
             <?php foreach ($users as $user) : ?>
              <tr>
                  <td><?php echo $this->escapeHtml(stripcslashes($user->first_name)).' '.$this->escapeHtml(stripcslashes($user->last_name));?></td>
					<td><?php echo ($user->avtar_url != "")?'<img src="'.$user->avtar_url.'" height="50" width="50" />':'No Avtar';?></td>
					<td><?php echo $this->escapeHtml($user->user_name);?></td>
					<td><?php echo $this->escapeHtml($user->user_type);?></td>
					<td><?php echo $this->escapeHtml($user->email);?></td>
					<td><?php echo date('d-m-Y',strtotime($user->created_date)); ?></td>
					<td><?php echo ($user->last_login != '')?date('d-m-Y H:i:s',strtotime($user->last_login)):'00-00-0000 00:00:00';?></td>
					<!--<td><span class="label label-sm enablechat disablechat label-<?php //echo (array_key_exists($user->chat, $settingArray))?$settingArray[$user->chat]:'default';?>" id="<?php// echo $user->id;?>"><?php //echo ($user->chat == 1)?'Enabled':'Disabled'; ?></span></td>
					<td><span class="label label-sm enablesms disablesms label-<?php //echo (array_key_exists($user->sms, $settingArray))?$settingArray[$user->sms]:'default';?>" id="<?php //echo $user->id;?>"><?php //echo ($user->sms == 1)?'Enabled':'Disabled'; ?></span></td>
					<td><span class="label label-sm enableemail disableemail label-<?php// echo (array_key_exists($user->email_status, $settingArray))?$settingArray[$user->email_status]:'default';?>" id="<?php //echo $user->id;?>"><?php //echo ($user->email_status == 1)?'Enabled':'Disabled'; ?></span></td>-->
					<td><span class="label label-sm status label-<?php echo (array_key_exists($user->status_id, $statusArray))?$statusArray[$user->status_id]:'default';?>" id="<?php echo $user->id;?>"><?php echo $this->escapeHtml($user->status);?></span></td>
					<td>
						<a class="btn default btn-xs default" href="<?php echo $this->url('admin/userfeaturesetting',array('id' => $user->id));?>"><i class="fa fa-briefcase" title="Chat Status" ></i></a>
						<a class="btn default btn-xs grey" href="<?php echo $this->url('admin/usersmedia',array('user_id' => $user->id));?>"><i class="fa fa-picture-o" title="manage images" ></i></a>
						<a class="btn default btn-xs grey" href="<?php echo $this->url('admin/users',array('action'=>'edit', 'id' => $user->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
						<a class="btn default btn-xs grey" href="<?php echo $this->url('admin/users',array('action'=>'delete', 'id' => $user->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
						<a class="btn default btn-xs grey" href="<?php echo $this->url('admin/userrights',array('action'=>'assign', 'id' => $user->id));?>"><i class="fa fa-key" title="assign roles" ></i></a>
						<input class="checkboxes" type="checkbox" value="<?php echo $user->id;?>">
					</td>
				</tr>
				<?php endforeach; ?>
			<?php }else{ echo "<tr><td colspan='8'>No record found !!</td></tr>"; } ?>
            </tbody>
          </table>
          <?php 
			echo 
			$this->paginationControl(
					$users,  
					'sliding', 
					array('partial/paginator.phtml', 'Admin'),  
					array('route' => 'admin/users') 
				);
			?>
        </div>
      </div>
    </div>
  </div>
</div>
