<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-briefcase"></i>Service Categories List </div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/servicecategory', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Service Category </a> </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
			<table class="table table-hover table-bordered table-striped">
				<thead>
					<tr>
						<th>Category Name</th>
						<th>Parent</th>
                                                <th>Total Bookings</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php if (isset($servicecats) && count($servicecats)>0) : ?>
						<?php foreach ($servicecats as $servicecat) : ?>
						<tr>
							<td><?php echo $this->escapeHtml($servicecat->category_name);?></td>
							<td><?php echo $this->escapeHtml($servicecat->parents);?></td>
                                                        <td><?php echo $model->getTotalPerCategory($servicecat->id);?></td>
							<td>
								<a class="btn default btn-xs" href="<?php echo $this->url('admin/servicecategory',array('action'=>'edit', 'id' => $servicecat->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
								<a class="btn default btn-xs" href="<?php echo $this->url('admin/servicecategory',array('action'=>'delete', 'id' => $servicecat->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
							</td>
						</tr>
						<?php endforeach; ?>
					<?php endif; ?>
				</tbody>
			</table>
		<?php 
		echo $this->paginationControl(
						$servicecats,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/servicecategory')  // the route to link to when a user clicks a control link
					);
		?>
		</div>
      </div>
    </div>
  </div>
</div>
