<?php 
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-desktop"></i>Advertisement Plans List</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/advertisementplan', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Advertisement Plan </a> </div>
        
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>Plan Name</th>
                <th>Page</th>
                <th>Advertisement</th>
                <th>Duration</th>
                <th>Price</th>
                <th width="225" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
              </tr>
            </thead>
            <tbody>
              <?php if (isset($advertisementplans) && count($advertisementplans)>0) : ?>
              <?php foreach ($advertisementplans as $advertisementplan) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($advertisementplan->plan_name);?></td>
                <td><?php echo $this->escapeHtml($advertisementplan->page_name);?></td>
                <td><?php echo $this->escapeHtml($advertisementplan->banner_name);?></td>
                <td><?php echo $this->escapeHtml($advertisementplan->duration." ".$advertisementplan->duration_in);?></td>
                <td><?php echo "$ ".$this->escapeHtml($advertisementplan->price);?></td>
                <td>
                    <a class="btn default btn-xs default" href="<?php echo $this->url('admin/advertisementplan',array('action'=>'edit', 'id' => $advertisementplan->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
		    <a class="btn default btn-xs default" href="<?php echo $this->url('admin/advertisementplan',array('action'=>'delete', 'id' => $advertisementplan->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
		    <input class="checkboxes" type="checkbox" value="<?php echo $advertisementplan->id;?>">
		</td>
              </tr>
              <?php endforeach; ?>
              <?php endif; ?>
            </tbody>
          </table>
          <?php echo $this->paginationControl(
                  $advertisementplans,  // the paginator object
		  'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
		  array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
		  array('route' => 'admin/advertisementplan')  // the route to link to when a user clicks a control link
		);
          ?>
        </div>
      </div>
    </div>
  </div>
</div>
