<?php
$status = (isset($status) && count($status) > 0) ? $status->toArray() : array(); 
$statusArray = array('1' => 'success', '2' => 'warning');
?>
<div class="row">
    <div class="col-md-12 col-sm-12">

        <?php if (isset($successMsgs) && count($successMsgs) > 0): ?>
            <div class="note note-success">
                <?php
                foreach ($successMsgs as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <?php if (isset($errors) && count($errors) > 0): ?>
            <div class="note note-danger">
                <?php
                foreach ($errors as $msg) {
                    echo '<p> ' . $msg . ' </p>';
                }
                ?>
            </div>
        <?php endif; ?>
        <div class="note" id="error" style="display:none;"></div>

        <div class="portlet grey box">
            <div class="portlet-title">
                <div class="caption"> <i class="fa fa-file-text"></i>Faqs List</div>
                <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/faqs', array('action' => 'add')); ?>"> <i class="fa fa-pencil"></i> Add New Faq </a> </div>
                <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
                    <?php
                    if (isset($status) && count($status) > 0) {
                        echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
                        foreach ($status as $value) {
                            echo '<option value="' . $value['status_id'] . '" >' . ucwords($value['status']) . '</option>';
                        }
                        echo '</select>';
                    }
                    ?>
                    <button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/faqs', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>User Type</th>
                                <th>Index</th>
                                <th>Question</th>
                                <th>Answer</th>
                                <th>Display Order</th>
                                <th>Created On</th>
                                <th>Status</th>
                                <th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (isset($faqs) && count($faqs) > 0) : ?>
                                <?php foreach ($faqs as $faq) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($faq->user_type); ?></td>
                                        <td><?php echo $this->escapeHtml($faq->index_name); ?></td>
                                        <td><?php echo $this->escapeHtml($faq->question); ?></td>
                                        <td><?php echo substr($this->escapeHtml($faq->answer),0,50).'...'; ?></td>
                                        <td><?php echo $this->escapeHtml($faq->order_by); ?></td>
                                        <td><?php echo $this->escapeHtml(date('d-m-Y', strtotime($faq->created_on))); ?></td>
                                        <td><span class="status label label-sm label-<?php echo (array_key_exists($faq->status_id, $statusArray)) ? $statusArray[$faq->status_id] : 'default'; ?>" id="<?php echo $faq->id; ?>"><?php echo $this->escapeHtml(ucwords($faq->status)); ?></span></td>
                                        <td>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/faqs', array('action' => 'edit', 'id' => $faq->id)); ?>"><i class="fa fa-edit" title="edit" ></i></a>
                                            <a class="btn default btn-xs" href="<?php echo $this->url('admin/faqs', array('action' => 'delete', 'id' => $faq->id)); ?>"><i class="fa fa-trash-o" title="delete" ></i></a>
                                            <input class="checkboxes" type="checkbox" value="<?php echo $faq->id; ?>">
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php
                    echo
                    $this->paginationControl(
                            $faqs, 'sliding', array('partial/paginator.phtml', 'Admin'), array('route' => 'admin/faqs')
                    );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
