<?php
	
	$title = 'Manage Group Permission';
	$this->headTitle($title);
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'admin/grouprights',
		array(
			'action' => 'assign',
			'id'     => $this->id,
		)
	));
	
	$form->prepare();
?>

<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/usertype"> <i class="fa fa-pencil"></i>User Groups List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
	  <div class="form-body">
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id'));?>
		<input type="hidden" name="group_id" value="<?php echo isset($group_id) ? $group_id : '' ; ?>">
		<div class="form-body">
			<h3 class="form-section">Group Rights Info</h3>
			<div class="row">
				<div class="form-group">
					<label class="control-label col-md-3">Group Name:</label>
						<div class="col-md-9">
							<?php echo isset($group_name) ? $group_name : '' ; ?>	
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="portlet">
						<div class="portlet-body">
							<div class="table-responsive">
								<table class="table table-striped table-bordered table-advance table-hover">
									<thead>
										<tr>
											<th>Module Name</th>
											<th>Add</th>
											<th>Edit</th>
											<th>View</th>
											<th>Delete</th>
										</tr>
									</thead>
									<tbody>
										<?php if (isset($fields) && count($fields)>0): ?>
											<?php foreach ($fields as $fld): ?>
												<input type="hidden" name="module_id[]" value="<?php echo $fld; ?>">
												<tr>
													<td>
														<?php echo isset($module_name[$fld]) ? $module_name[$fld] : '' ; ?>
													</td>
													<td>
														<?php 
															if(isset($GroupRights['add_'.$fld]) && !empty($GroupRights['add_'.$fld])){
																$field = $form->get('can_add['.$fld.']')->setAttributes(array('checked'=>'checked')); 
															}else{
																$field = $form->get('can_add['.$fld.']'); 		
															}
														?>
														<?php echo $this->formCheckbox($field); ?>		
													</td>
													<td>
														<?php 
															if(isset($GroupRights['edit_'.$fld]) && $GroupRights['edit_'.$fld] == "1"){
																$field = $form->get('can_edit['.$fld.']')->setAttributes(array('checked'=>'checked')); 
															}else{
																$field = $form->get('can_edit['.$fld.']'); 
															}
														?>
														<?php echo $this->formCheckbox($field); ?>		
													</td>
													<td>
														<?php 
															if(isset($GroupRights['view_'.$fld]) && $GroupRights['view_'.$fld] == "1"){
																$field = $form->get('can_view['.$fld.']')->setAttributes(array('checked'=>'checked')); 
															}else{
																$field = $form->get('can_view['.$fld.']'); 
															}
														?>
														<?php echo $this->formCheckbox($field); ?>		
													</td> 
													<td>
														<?php 	
															if(isset($GroupRights['del_'.$fld]) && $GroupRights['del_'.$fld] == "1"){
																$field = $form->get('can_del['.$fld.']')->setAttributes(array('checked'=>'checked')); 
															}else{
																$field = $form->get('can_del['.$fld.']'); 	
															}	
														?>
														<?php echo $this->formCheckbox($field); ?>		
													</td>
												</tr>	
											<?php endforeach; ?>
										<?php endif?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>	
			</div>
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<button type="submit" class="btn green">Submit</button>
					<button type="reset" class="btn default">Reset</button>
				</div>
			</div>				
		</div>
		<?php  echo $this->form()->closeTag();?>
	  </div>
	</div>
</div>
