<?php 
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
$invoiceStatusArray= array('0' => 'danger', '1' => 'success', '2' => 'warning');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-book"></i>Banner Bookings List</div>
        <div class="actions"> 
			<a class="btn default btn-sm" href="<?php echo (count($this->postedData) > 0)?$this->url('admin/bannerbookings', array('action'=>'export')).'?'.http_build_query($this->postedData):$this->url('admin/bannerbookings', array('action'=>'export'));?>"> <i class="fa fa-download"></i> Export </a>
			<a class="btn default btn-sm" href="<?php echo $this->url('admin/bannerbookings', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Banner Booking </a> 
        </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/bannerbookings', array('action'=>'changestatus'));?>' ><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped" id='bannerBookingTable' data-path='<?php echo $this->url('admin/bannerbookings');?>'>
            <thead>
              <tr>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'name') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='name'>Customer</th>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'plan') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='plan'>Booked Plan</th>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'date') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='date'>Order Date</th>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'start_date') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='start_date'>Start Date</th>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'end_date') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='end_date'>End Date</th>
                <th>Order Amount</th>
                 <th>Currency</th>
                <th>Payment Status</th>
                <th>Status</th>
                <th width="110" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
              </tr>
            </thead>
            <tbody>
              <?php if (isset($bannerbookings) && count($bannerbookings)>0) : ?>
              <?php foreach ($bannerbookings as $bannerbooking) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($bannerbooking->first_name." ".$bannerbooking->last_name);?></td>
                <td><?php echo $this->escapeHtml($bannerbooking->sale_item_details);?></td>
                <td><?php echo $this->escapeHtml(date('d-m-Y',strtotime($bannerbooking->booking_date)));?></td>
                <td><?php echo $this->escapeHtml(date('d-m-Y',strtotime($bannerbooking->start_date)));?></td>
                <td><?php echo $this->escapeHtml(date('d-m-Y',strtotime($bannerbooking->end_date)));?></td>
                <td><?php echo "$ ".$this->escapeHtml($bannerbooking->invoice_total);?></td>
                <td><?php echo $this->escapeHtml($bannerbooking->currency);?></td>
                <td><span class="label label-sm label-<?php  echo (array_key_exists($bannerbooking->invoice_status, $invoiceStatusArray))?$invoiceStatusArray[$bannerbooking->invoice_status]:'default';?>" ><?php echo $this->escapeHtml(ucwords($bannerbooking->payment_status));?></span></td>
                <td><span class="label label-sm status label-<?php  echo (array_key_exists($bannerbooking->status_id, $statusArray))?$statusArray[$bannerbooking->status_id]:'default';?>" id="<?php echo $bannerbooking->id;?>"><?php echo $this->escapeHtml(ucwords($bannerbooking->status));?></span></td>
                <td>
					<a class="btn default btn-xs default" href="<?php echo $this->url('admin/banneruploads',array('booking_id' => $bannerbooking->id));?>"><i class="fa fa-upload" title="Upload Banners" ></i></a>
					<a class="btn default btn-xs default" href="<?php echo $this->url('admin/bannerbookings',array('action'=>'edit', 'id' => $bannerbooking->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
					<a class="btn default btn-xs default" href="<?php echo $this->url('admin/bannerbookings',array('action'=>'delete', 'id' => $bannerbooking->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
					<input class="checkboxes" type="checkbox" value="<?php echo $bannerbooking->id;?>">
				</td>
              </tr>
              <?php endforeach; ?>
              <?php endif; ?>
            </tbody>
          </table>
          <?php 
		echo $this->paginationControl(
						$bannerbookings,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/bannerbookings', 'routeParams' => $this->postedData)  // the route to link to when a user clicks a control link
					);
?>
        </div>
      </div>
    </div>
  </div>
</div>
