<?php

$title = 'Delete Site Setting'; 
$this->headTitle($title);
?>

<div class="col-md-6"> 
  <div class="portlet box grey">
    <div class="portlet-title"> 
      <div class="caption"> <i class="fa fa-gears"></i>Delete </div>
    </div>
    <div class="portlet-body">
      <div class="alert alert-block alert-danger fade in">
        <h4 class="alert-heading"><?php echo $this->escapeHtml($title); ?></h4>
        <p>Are you sure that you want to delete this site setting '<?php echo $this->escapeHtml($sitesetting->setting_key); ?>'</p>
        <p>&nbsp;</p>
		<?php
		$url = $this->url('admin/sitesettings', array(
			'action' => 'delete',
			'id'     => $this->id,
		));
		?>
        <form action="<?php echo $url; ?>" method="post">
          <div>
            <input type="hidden" name="id" value="<?php echo (int) $sitesetting->id; ?>" />
            <input type="submit" name="del" value="Yes" class="btn red" />
            <input type="submit" name="del" value="No" class="btn blue" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

