<?php 
$form->setAttribute('action', $this->url('admin/test',array('action' => 'add'))); // $this->url('pages', array('action' => 'add'))
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'horizontal');
$form->prepare();
//echo $this->formCollection($form); 
?> 

<div class="portlet box grey">
	<div class="portlet-title">
		<div class="caption"> <i class="fa fa-reorder"></i> Add Test</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/test"> <i class="fa fa-list"></i> Test List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-share"></i> Back</a> </div>
    </div>
    <div class="portlet-body form">
		<div class="form-body">
			<?php if (isset($errors) && count($errors)>0): ?>  
			<div class="alert alert-danger"><button class="close" data-close="alert"></button>
				<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
			</div>
			<?php endif;?>
		
			<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
			<div class="form-body">
				<h3 class="form-section">Test Info</h3>
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('name'); ?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('contactNumber'); ?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('status');?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formRadio($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('language');?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formMultiCheckbox($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('country');?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formSelect($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				<div class="row">
					<div class="col-md-6">
						<?php $field = $form->get('document');?>
						<div class="form-group <?php echo ($this->formElementErrors($field) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($field); ?></label>
							<div class="col-md-9">
								<?php echo $this->formFile($field);?>
								<span class="help-block">
									 <?php echo strip_tags($this->formElementErrors($field));?>
								</span>
							</div>
						</div>
					</div>
					<!--/span-->
				</div>
				<!--/row-->
				
			</div>
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="reset" class="btn default">Reset</button>
						</div>
					</div>
					<div class="col-md-6">
					</div>
				</div>
			</div>
			<?php  echo $this->form()->closeTag();?>
			<!-- END FORM-->
		</div>
	</div>
</div>


