<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('admin/certifications', array('action' => 'add')));
	$form->prepare(); 
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> Add User Certification </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/UserCertifications"> <i class="fa fa-pencil"></i>Certifications List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
	  <div class="form-body">
			<!--PAGE CONTENT BEGINS-->
			<?php if (isset($errors) && count($errors)>0): ?>  
			<div class="alert alert-danger"><button class="close" data-close="alert"></button>
				<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
			</div>
			<?php endif;?>
			
			<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
			<div class="form-body">
				<h3 class="form-section">User Certification Info</h3>
				<div class="row">
					<div class="col-md-6">
					<?php $user_id = $form->get('user_id'); ?>		
						<div class="form-group  <?php echo ($this->formElementErrors($user_id) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($user_id); ?></label>
							<div class="col-md-9">
								<?php echo $this->formSelect($user_id); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($user_id); ?>
								</span>
							</div>
						</div>
					</div>
					
					<div class="col-md-6">
					<?php $title = $form->get('title'); ?>
						<div class="form-group  <?php echo ($this->formElementErrors($title) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($title); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($title); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($title); ?>
								</span>
							</div>
						</div>
					</div>
				</div>
				<!--/row-->	
				<div class="row">
					<div class="col-md-6">
					<?php $logo = $form->get('logo'); ?>		
						<div class="form-group  <?php echo ($this->formElementErrors($logo) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($logo); ?></label>
							<div class="col-md-9">
								<?php echo $this->formFile($logo); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($logo); ?>
								</span>
							</div>
						</div>
					</div>
					
					<div class="col-md-6">
					<?php $organization_name = $form->get('organization_name'); ?>
						<div class="form-group  <?php echo ($this->formElementErrors($organization_name) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($organization_name); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($organization_name); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($organization_name); ?>
								</span>
							</div>
						</div>
					</div>
				</div>
				<!--/row-->	
				<div class="row">
                                    <div class="col-md-6">
					<?php $professional_licence_number = $form->get('professional_licence_number'); ?>		
						<div class="form-group  <?php echo ($this->formElementErrors($professional_licence_number) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($professional_licence_number); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($professional_licence_number); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($professional_licence_number); ?>
								</span>
							</div>
						</div>
					</div>
					<div class="col-md-6">
					<?php $certification_date = $form->get('certification_date'); ?>		
						<div class="form-group  <?php echo ($this->formElementErrors($certification_date) != "")?"has-error":"";?>">
							<label class="control-label col-md-3"><?php echo $this->formLabel($certification_date); ?></label>
							<div class="col-md-9">
								<?php echo $this->formInput($certification_date); ?>	
								<span class="help-block">
									 <?php echo $this->formElementErrors($certification_date); ?>
								</span>
							</div>
						</div>
					</div>
					
				</div>
				<!--/row-->	
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <?php $validity = $form->get('validity'); ?>
                                        <div class="form-group  <?php echo ($this->formElementErrors($validity) != "") ? "has-error" : ""; ?>">
                                            <label class="control-label col-md-3"><?php echo $this->formLabel($validity); ?></label>
                                            <div class="col-md-9">
                                                <?php echo $this->formInput($validity); ?>	
                                                <span class="help-block">
                                                    <?php echo $this->formElementErrors($validity); ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <?php $status_id = $form->get('status_id'); ?>
                                        <div class="form-group  <?php echo ($this->formElementErrors($status_id) != "") ? "has-error" : ""; ?>">
                                            <label class="control-label col-md-3"><?php echo $this->formLabel($status_id); ?></label>
                                            <div class="col-md-9">
                                                <?php echo $this->formSelect($status_id); ?>	
                                                <span class="help-block">
                                                    <?php echo $this->formElementErrors($status_id); ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
			</div>	
			<div class="form-actions fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn green">Submit</button>
							<button type="reset" class="btn default">Reset</button>
						</div>
					</div>
					<div class="col-md-6">
					</div>
				</div>
			</div>
			<?php  echo $this->form()->closeTag();?>
			<!-- END FORM-->
		</div>
	</div>
</div>
