<?php $statusArray = array('12' => 'success', '13' => 'warning', '14' => 'danger');?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <div><?php  if (isset($messages) && is_array($messages) && count($messages)>0) {
					foreach ($messages as $message) {
						echo $message."<br />";
					}
		         };  ?></div>
	<?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
	<?php endif;?>
	<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
	<?php endif;?>
	<div class="note" id="error" style="display:none;"></div>
	
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-user"></i>Certifications List </div>
        <div class="actions"> 
			<a class="btn default btn-sm" href="<?php echo (count($this->postedData) > 0)?$this->url('admin/certifications', array('action'=>'export')).'?'.http_build_query($this->postedData):$this->url('admin/certifications', array('action'=>'export'));?>"> <i class="fa fa-download"></i> Export </a> 
			<a class="btn default btn-sm" href="<?php echo $this->url('admin/certifications', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New User Certification </a> 
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
            <thead>
              <tr>
                  <th>User</th>
                  <th>Title</th>
                  <th>Logo</th>
                  <th>Professional Licence Number</th>
                  <th>Organization Name</th>
                  <th>Certification Date</th>
                  <th>Expiration Date</th>
                  <th>Status</th>
                  <th>Action</th>
              </tr>
            </thead> 
            <tbody>
             <?php if (isset($certifications)) : ?>
             <?php foreach ($certifications as $certification) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml(ucwords($certification->user_name)); ?></td>
                    <td><?php echo $this->escapeHtml($certification->title); ?></td>
                    <td><img class="" height="50" width="50" src="<?php echo str_replace('Original', 'Small', $this->escapeHtml($certification->logo)); ?>" /></td>
                    <td><?php echo $this->escapeHtml($certification->professional_licence_number); ?></td>
                    <td><?php echo $this->escapeHtml($certification->organization_name); ?></td>
                    <td><?php echo date('d-m-Y', strtotime($certification->certification_date)); ?></td>
                    <td><?php echo date('d-m-Y', strtotime($certification->validity)); ?></td>
                    <td><span class="label label-sm status label-<?php echo (array_key_exists($certification->status_id, $statusArray))?$statusArray[$certification->status_id]:'default';?>" id="<?php echo $certification->id;?>"><?php echo $this->escapeHtml(ucwords($certification->status));?></span></td>
                    <td>
                        <a class="btn default btn-xs" href="<?php echo $this->url('admin/certifications', array('action' => 'edit', 'id' => $certification->id)); ?>"><i class="fa fa-edit" title="edit" ></i></a>
                        <a class="btn default btn-xs" href="<?php echo $this->url('admin/certifications', array('action' => 'delete', 'id' => $certification->id)); ?>"><i class="fa fa-trash-o" title="delete" ></i></a>
                    </td>
                </tr>
				<?php endforeach; ?>
			<?php endif; ?>
            </tbody>
          </table>
          <?php 
			echo 
			$this->paginationControl(
					$certifications, 
					'sliding',   
					array('partial/paginator.phtml', 'Admin'),  
					array('route' => 'admin/certifications')  
				);
			?>
        </div>
      </div>
    </div>
  </div>
</div>
