<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array('controller' => 'consumer', 'action' => 'compose')));
$form->prepare();
?>
<!-- CONTENT START HERE -->
<div id="content">
    <div id="banner">
        <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/practitioner-about.jpg" alt="" />
    </div>
    <div class="main dashboard">
        <ul id="breadcrumb">
            <li>
                <a href="<?php echo $this->url('home'); ?>">Home</a>
            </li>
            <li>
                <a href="<?php echo $this->url('consumer', array('action' => 'dashboard')); ?>">
                    Dashboard
                </a>
            </li>
            <li>
                Compose message
            </li>
        </ul>
        <h2>
            Dashboard
            <span>
                <small>
                    &nbsp;
                </small>
            </span>
        </h2>

        <!-- Practitioner Section-->
        <div class="practitioner-section">
            <!-- start profile right panel here-->
            <div class="profile-add-left">
                <div class="profile-wrapper">
                    <?php if (!empty($avtar_url)) { ?>
                        <img src="<?php echo $avtar_url; ?>" alt="" />
                    <?php } else { ?> 
                        <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/profile-pic.jpg" alt="" />
                    <?php } ?>
                    <!----        
                    <div class="social-icon">
                            <ul>
                                    <li><a class="facebook" href="javascript:;">Facebook</a></li>
                                    <li><a class="twitter" href="javascript:;">twitter</a></li>
                                    <li><a class="google" href="javascript:;">google</a></li>
                                    <li><a class="linkdin" href="javascript:;">linkdin</a></li>
                            </ul>
                    </div>
                    ---->
                </div>
                <div class="dashboard-nav">
                    <ul>
                        <li>
                            <a href="javascript:;" class="active" >Messages</a><span><?php echo isset($notifications['inbox']) ? $notifications['inbox'] : ''; ?></span>
                            <ul class="dashboard-submenu" style="display: block;" >
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/compose">Compose</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/inbox">Inbox  ( <?php echo isset($notifications['inbox']) ? $notifications['inbox'] : ''; ?> )</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/sent">Sent</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/trash">Trash</a></li>
                            </ul>
                        </li>
                        <li><a id="total_notification" href="javascript:;">Notification</a><?php echo (isset($notifications['total']) && $notifications['total'] > 0) ? '<span>' . $notifications['total'] . '</span>' : ''; ?>
                            <ul class="dashboard-submenu">
                                <li id='booking_notification' ><?php echo (isset($notifications['booking']) && $notifications['booking'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=booking" >' . $notifications['booking'] . ' New Bookings</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=booking">No New Bookings</a>'; ?></li>
                                <!--<li><?php echo (isset($notifications['review']) && $notifications['review'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=review" ">' . $notifications['review'] . ' New Review</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=review">No New Review</a>'; ?></li>
                                <li><?php echo (isset($notifications['invites']) && $notifications['invites'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '">' . $notifications['invites'] . ' Invite</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '">No Invites</a>'; ?></li>-->
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->basePath(); ?>/consumer/settings">Setting</a></li>
                    </ul>
                </div>
            </div>
            <!-- end profile left panel here-->
            <div class="profile-add-right">
                <div class="book-block">
                    <div class="rating-top">
                        <div class="head">
                            <h3><?php echo!empty($first_name) ? $first_name : ''; ?>&nbsp;<?php echo!empty($last_name) ? $last_name : ''; ?></h3>
                        </div>
                    </div>
                </div>
                <div class="message-section">
                    <h3>Compose</h3>
                    <div class="compose-message">
                        <?php echo $this->form()->openTag($form); ?>
                        <div class="row">
                            <?php $to = $form->get('to'); ?>
                            <?php echo $this->formLabel($to); ?>
                            <?php echo $this->formSelect($to); ?>
                            <?php echo strip_tags($this->formElementErrors($to)); ?>
                        </div>
                        <div class="row">
                            <?php $subject = $form->get('subject'); ?>
                            <?php echo $this->formLabel($subject); ?>
                            <?php echo $this->formInput($subject); ?>
                            <?php echo strip_tags($this->formElementErrors($subject)); ?>
                        </div>
                        <div class="row">
                            <?php $message = $form->get('message'); ?>
                            <?php echo $this->formLabel($message); ?>
                            <?php echo $this->formTextarea($message); ?>
                            <?php echo strip_tags($this->formElementErrors($message)); ?>
                        </div>
                        <div class="message-sendButton">
                            <input type="submit" value="Send" />
                            <a href="<?php echo $this->basePath(); ?>/consumer/inbox">DISCARD</a>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
            <!-- start profile right panel here-->
        </div>
        <!-- /Practitioner Section-->
    </div>
</div>
<!-- CONTENT END HERE -->
