<div id="content">
    <div id="banner">
        <?php if (isset($banners) && is_array($banners) && count($banners) > 0):?>
        <img src="<?php echo isset($banners[0]['banner_url'])?$banners[0]['banner_url']:'';?>" alt="" />
        <?php endif;?>
    </div>
    <div class="main dashboard">
        <ul id="breadcrumb">
            <li>
                <a href="<?php echo $this->url('home'); ?>">Home</a>
            </li> 
            <li>
                <a href="<?php echo $this->url('consumer', array('action' => 'dashboard')); ?>">
                    Dashboard
                </a>
            </li>
            <li>
                Settings
            </li>
        </ul>
        <h2>
            Dashboard
            <span>
                <small>
                    &nbsp;
                </small>
            </span>
        </h2>

        <!-- Practitioner Section-->
        <div class="practitioner-section">
            <div class="success-msg" style="display: none;"></div>
            <div class="error-msg" style="display: none;"></div>
            <!-- start profile right panel here-->
            <div class="profile-add-left">
                <div class="profile-wrapper">
                    <?php if (!empty($avtar_url)) { ?> 
                        <img src="<?php echo $avtar_url; ?>" alt="" />
                    <?php } else { ?>
                        <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/profile-pic.jpg" alt="" />
                    <?php } ?>
                    <!---
                    <div class="social-icon">
                        <ul>
                            <li><a class="facebook" href="javascript:;">Facebook</a></li>
                            <li><a class="twitter" href="javascript:;">twitter</a></li>
                            <li><a class="google" href="javascript:;">google</a></li>
                            <li><a class="linkdin" href="javascript:;">linkdin</a></li>
                        </ul>
                    </div>
                    ----->
                </div>
                <div class="dashboard-nav">
                    <ul>
                        <li>
                            <a href="javascript:;">Messages</a><span><?php echo isset($notifications['inbox']) ? $notifications['inbox'] : ''; ?></span>
                            <ul class="dashboard-submenu">
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/compose">Compose</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/inbox">Inbox  ( <?php echo isset($notifications['inbox']) ? $notifications['inbox'] : ''; ?> )</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/sent">Sent</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/consumer/trash">Trash</a></li>
                            </ul>
                        </li>
                        <li><a id="total_notification" href="javascript:;">Notification</a><?php echo (isset($notifications['total']) && $notifications['total'] > 0) ? '<span>' . $notifications['total'] . '</span>' : ''; ?>
                            <ul class="dashboard-submenu">
                                <li id='booking_notification' ><?php echo (isset($notifications['booking']) && $notifications['booking'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=booking" >' . $notifications['booking'] . ' New Bookings</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=booking">No New Bookings</a>'; ?></li>
                                <!--<li><?php echo (isset($notifications['review']) && $notifications['review'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=review" ">' . $notifications['review'] . ' New Review</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '?tab=review">No New Review</a>'; ?></li>
                                <li><?php echo (isset($notifications['invites']) && $notifications['invites'] > 0) ? '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '">' . $notifications['invites'] . ' Invite</a>' : '<a href="' . $this->url('consumer', array('action' => 'dashboard')) . '">No Invites</a>'; ?></li>-->
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->basePath(); ?>/consumer/settings">Setting</a></li>
                    </ul>
                </div>
            </div>
            <!-- end profile left panel here-->
            <div class="profile-add-right">
                <div class="book-block">
                    <div class="rating-top">
                        <div class="head">
                            <h3><?php echo!empty($first_name) ? $first_name : ''; ?>&nbsp;<?php echo!empty($last_name) ? $last_name : ''; ?></h3>
                        </div>
                    </div>
                </div>
                <div class="setting-section">
                    <div id="errorMsg" style="text-align:center;color:red;"></div>
                    <div id="successMsg" style="text-align:center;color:green;"></div>
                    <div class="password">
                        <?php echo $this->form()->openTag($form); ?>
                        <h4>PASSWORD CHANGE</h4>
                        <div class="info-text">
                            Password are case sensitive and must be at least 6 charachters.<br>
                            A good password should contain a mix of capital and lower case letters, numbers and symbols.
                        </div>
                        <div class="row">
                            <?php $old_pass = $form->get('old_pass'); ?>
                            <?php echo $this->formLabel($old_pass); ?>
                            <?php echo $this->formInput($old_pass); ?>
                            <?php echo strip_tags($this->formElementErrors($old_pass)); ?>
                        </div> 
                        <div class="row">
                            <?php $Pass = $form->get('Pass'); ?>
                            <?php echo $this->formLabel($Pass); ?>
                            <?php echo $this->formInput($Pass); ?>
                            <?php echo strip_tags($this->formElementErrors($Pass)); ?>
                        </div> 
                        <div class="row">
                            <?php $confirm_password = $form->get('confirm_password'); ?>
                            <?php echo $this->formLabel($confirm_password); ?>
                            <?php echo $this->formInput($confirm_password); ?>
                            <?php echo strip_tags($this->formElementErrors($confirm_password)); ?>
                        </div> 
                        <div class="row">
                            <label>&nbsp;</label>
                            <input type="submit" class="black" value="Change Password" />
                            <input type="reset" value="Cancel" class="black">
                        </div> 
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <div class="password">
                        <h4>NOTIFICATIONS AND REMINDERS OF APPOINTMENTS </h4>
                        <div class="info-text">
                                Please select how you want to receive notifications and reminders
                        </div>
                        <div class="selection">
                            <div class="row">
                                <input type="checkbox" id="feature_email" class="feature_chk" <?php echo ($featureData['email'] == 1) ? "checked='checked' value='1'" : "value='0'"; ?> >
                                <label>Personal e-mail </label>
                            </div>
                            <div class="row">
                                <input type="checkbox" id="feature_sms" class="feature_chk" <?php echo ($featureData['sms'] == 1) ? "checked='checked' value='1'" : "value='0'"; ?> >
                                        <label>SMS (If the option is available with your Practitioner)<!--(Please note that a standard plan doesn't allow to use this feature)--></label>
                            </div>
                            <div class="row">
                                <input type="checkbox" id="feature_chat" class="feature_chk" <?php echo ($featureData['chat'] == 1) ? "checked='checked' value='1'" : "value='0'"; ?> >
                                <label>Chat </label>    
                            </div>
                            <input type="hidden" id="feature_table_id" value="<?php echo isset($featureData['id']) ? $featureData['id'] : ''; ?>"> 
                       </div> 
                    </div>
                    <div class="password">
                        <form> 
                            <h4>NEWSLETTERS </h4>
                            <div class="selection">
                                <div class="row">
                                    <input type="radio" name="newsletter-chk" <?php echo ($featureData['newsletter'] == 4) ? "checked='checked'" : ""; ?> value="4" >
                                    <label>OvEssence and Practitioners may send me newsletters</label>
                                </div>
                                <div class="row">
                                    <input type="radio" name="newsletter-chk" <?php echo ($featureData['newsletter'] == 1) ? "checked='checked'" : ""; ?> value="1" >
                                    <label>OvEssence may send me newsletters</label>
                                </div>
                                <div class="row">
                                    <input type="radio" name="newsletter-chk" <?php echo ($featureData['newsletter'] == 2) ? "checked='checked'" : ""; ?> value="2" />
                                    <label>Practitioners may send me newsletters</label>
                                </div>
                                <div class="row">
                                    <input type="radio" name="newsletter-chk" <?php echo ($featureData['newsletter'] == 3) ? "checked='checked'" : ""; ?> value="3" >
                                    <label>I dont want to receive any newsletter</label>
                                </div>
                                <div style="" class="row">
                                    <input type="submit" value="Save" class="black" id="newsletter-submit">
                                </div>
                            </div> 
                        </form> 
                    </div>
                    <!----
                    <div class="password">
                        <h4>MANAGE ADVERTISING PREFERENCES  </h4>
                        <div class="info-text">
                            OvEssence does not directly share your personal information with advertisers, ad netowrks, publishers or any third party. <br>
                            We are committed to maintaining privacy around your Ovessence data. For more details take a look at our privacy policy 
                        </div>
                        <div class="selection">
                            <div class="row">
                                <input type="radio" name="radio">
                                <label>OvEssence may show me ads on third party websites</label>
                            </div>
                            <div class="row">
                                <input type="radio" name="radio">
                                <label>OvEssence may show me ads based on third party data</label>
                            </div>
                            <div style="padding-left:7px;" class="row">
                                <input type="submit" value="Save" class="black">
                            </div>
                        </div>
                    </div>
                    ---->
                    <div class="password">
                        <h4>CLOSE YOUR ACCOUNT  </h4>
                        <div class="info-text">
                            Why would you like to close your OvEssence account ? 
                        </div>
                        <div class="selection">
                            <?php
                            if (isset($reasonsList) && count($reasonsList) > 0) {
                                foreach ($reasonsList as $list) {
                                    ?>      
                                    <div class="row">
                                        <input type="radio" class="close-acc" name="close-acc" value="<?php echo isset($list['id']) ? $list['id'] : ''; ?>" >
                                        <label><?php echo isset($list['reason']) ? $list['reason'] : ''; ?></label>
                                    </div>
                                <?php
                                }
                            }
                            ?>
                            <div class="row">
                                <textarea id="other-reason" ></textarea>
                            </div>
                            <div class="row">
                                <input type="submit" value="CONTINUE" class="black" id="close-account" >
                                <input type="reset" value="CANCEL" class="black" id="reset-close-account">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- start profile right panel here-->

        </div>
        <!-- /Practitioner Section-->
    </div>
</div>
<!-- CONTENT END HERE -->
