<?php 

$title = 'Edit User Type';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/usertype',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
?>
<div class="portlet box grey">
  <div class="portlet-title">
    <div class="caption"> <i class="fa fa-reorder"></i> <?php echo $this->escapeHtml($title); ?> </div>
    <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->basePath()?>/admin/usertype"> <i class="fa fa-pencil"></i>Usertypes List</a> <a class="btn default btn-sm" href="javascript: history.go(-1);"> <i class="fa fa-pencil"></i> Back</a> </div>
  </div>
  <div class="portlet-body form">
	  <div class="form-body">
		<?php if (isset($errors) && count($errors)>0): ?>  
		<div class="alert alert-danger"><button class="close" data-close="alert"></button>
			<?php foreach ($errors as $field => $msg) {echo ucfirst(strtolower(strip_tags($this->formLabel($form->get($field)).' '.end($msg)))).'<br />';}?>
		</div>
		<?php endif;?>	
		
		<?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
		<div class="form-body">
			<!--PAGE CONTENT BEGINS-->
			<h3 class="form-section">User Type Info</h3>
			<div class="row">
				<div class="col-md-6">
					<?php $user_type = $form->get('user_type'); ?>
					<div class="form-group <?php echo ($this->formElementErrors($user_type) != "")?"has-error":"";?>">
						<label class="control-label col-md-3"><?php echo $this->formLabel($user_type); ?></label>
						<div class="col-md-9">
							<?php echo $this->formInput($user_type);?>
							<span class="help-block">
								 <?php echo strip_tags($this->formElementErrors($user_type));?>
							</span>
						</div>
					</div>
				</div>
				<!--/span-->
			</div>
			<!--/row-->
        </div>        
		<div class="form-actions fluid">
			<div class="row">
				<div class="col-md-6">
					<div class="col-md-offset-3 col-md-9">
						<button type="submit" class="btn green">Submit</button>
						<button type="reset" class="btn default">Reset</button>
					</div>
				</div>
				<div class="col-md-6"></div>
			</div>
		</div>
		<?php  echo $this->form()->closeTag();?>
		<!-- END FORM-->
	  </div>
  </div>
</div>
