<div class="row">
  <div class="col-md-12 col-sm-12">
	  <div>
		<?php if (isset($successMsgs) && count($successMsgs)>0): ?>
			<div class="note note-success">
				<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
			</div>
			<?php endif;?>
			<?php if (isset($errors) && count($errors)>0): ?>
			<div class="note note-danger">
				<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
			</div>
		<?php endif;?>
	  </div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-user"></i>User Types List</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/usertype', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New User Type </a> </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>Id</th>
				<th>User Type</th>
				<th>Action</th>
              </tr>
            </thead>
            <tbody>
             <?php if (isset($usertypes) && is_object($usertypes)) : ?>
             <?php foreach ($usertypes as $usertype) : ?>
              <tr>
					<td><?php echo $this->escapeHtml($usertype->id); ?></td>
					<td><?php echo $this->escapeHtml($usertype->user_type); ?></td>
					<td>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/usertype',array('action'=>'edit', 'id' => $usertype->id));?>"><i class="fa fa-edit" title="edit" ></i></a>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/usertype',array('action'=>'delete', 'id' => $usertype->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
						<a class="btn default btn-xs" href="<?php echo $this->url('admin/grouprights',array('action'=>'assign', 'id' => $usertype->id));?>"><i class="fa fa-key" title="assign roles" ></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			<?php endif; ?>
            </tbody>
          </table>
			<?php 
				echo 
				$this->paginationControl(
						$usertypes,  
						'sliding',  
						array('partial/paginator.phtml', 'Admin'),
						array('route' => 'admin/usertype') 
					);					
			?>
        </div>
      </div>
    </div>
  </div>
</div>
