<?php 
$form->setAttribute('action', '/admin/servicelanguages/');
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'service_lang_filter');
$form->prepare();
$status = (isset($status) && count($status)>0)?$status->toArray():array();
$statusArray = array('1' => 'success', '2' => 'warning', '3' => 'danger');
?>
<div class="row">
  <div class="col-md-12 col-sm-12">
	  <?php if (isset($successMsgs) && count($successMsgs)>0): ?>
		<div class="note note-success">
			<?php foreach ($successMsgs as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<?php if (isset($errors) && count($errors)>0): ?>
		<div class="note note-danger">
			<?php foreach ($errors as $msg) {echo '<p> '.$msg.' </p>';}?>
		</div>
		<?php endif;?>
		<div class="note" id="error" style="display:none;"></div>
    <div class="portlet grey box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gear"></i>Service Languages List</div>
        <div class="actions"> <a class="btn default btn-sm" href="<?php echo $this->url('admin/servicelanguages', array('action'=>'add'));?>"> <i class="fa fa-pencil"></i> Add New Service Language </a> </div>
        <div class="table-group-actions pull-right" style="margin: -4px 10px 0 0;">
			<?php if (isset($status)  &&  count($status)>0) { 
				echo '<select class="table-group-action-input form-control input-inline input-medium input-sm action" id="" ><option value="" >--Select Status--</option>';
					foreach ($status as $value) { echo '<option value="'.$value['status_id'].'" >'.ucwords($value['status']).'</option>';}
				echo '</select>';
			}?>
			<button class="btn btn-sm default table-group-action-submit changeStatus" data-path='<?php echo $this->url('admin/servicelanguages', array('action'=>'changestatus'));?>'><i class="fa fa-check"></i>Apply</button>
		</div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped" id="service_lang_table" data-path='<?php echo $this->url('admin/servicelanguages');?>'>
            <thead>
              <tr>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'language') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='language'>Service Language</th>
                <th class='<?php if (isset($this->postedData) && $this->postedData['sort_field'] == 'status') { echo strtolower('sorting_'.$this->postedData['sort_order']); } else { echo 'sorting'; }?>' data-field='status'>Status</th>
                <th width="161" class="table-checkbox" >Action <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/></th>
              </tr>
               <tr>
				<?php  echo $this->form()->openTag($form); ?>
				<td> <?php  echo $this->formInput($form->get('language_name')); ?> </td>
				<td> <?php  echo $this->formSelect($form->get('status_id')); ?> </td>
				<td>
					<button class="btn btn-sm default filter-submit margin-bottom search" data-form="service_lang_filter" data-tbl="service_lang_table"  data-path='<?php echo $this->url('admin/servicelanguages'); ?>' ><i class="fa fa-search"></i> Search</button>
				</td>
				<?php echo $this->form()->closeTag(); ?>
              </tr>
            </thead>
            <tbody>
              <?php if (isset($servicelanguages) && count($servicelanguages)>0) { ?>
              <?php foreach ($servicelanguages as $servicelanguage) : ?>
              <tr>
                <td><?php echo $this->escapeHtml($servicelanguage->language_name);?></td>
                <td><span class="label label-sm status label-<?php  echo (array_key_exists($servicelanguage->status_id, $statusArray))?$statusArray[$servicelanguage->status_id]:'default';?>" id="<?php echo $servicelanguage->id;?>"><?php echo $this->escapeHtml(ucwords($servicelanguage->status));?></span></td>
                <td>
					<a class="btn default btn-xs" href="<?php echo $this->url('admin/servicelanguages',array('controller'=>'page','action'=>'edit', 'id' => $servicelanguage->id));?>"><i class="fa fa-edit" title="edit" ></i></a> 
					<a class="btn default btn-xs" href="<?php echo $this->url('admin/servicelanguages',array('controller'=>'page','action'=>'delete', 'id' => $servicelanguage->id));?>"><i class="fa fa-trash-o" title="delete" ></i></a>
					<input class="checkboxes" type="checkbox" value="<?php echo $servicelanguage->id;?>">
				</td>
              </tr>
              <?php endforeach; ?>
              <?php }else{ ?>
              <tr><td colspan="3" > No Record Found..!! </td></tr>
              <?php } ?>
            </tbody>
          </table>
          <?php 
		echo $this->paginationControl(
						$servicelanguages,  // the paginator object
						'sliding',   // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
						array('partial/paginator.phtml', 'Admin'),  // the partial to use to render the control
						array('route' => 'admin/servicelanguages', 'routeParams' => $this->postedData)  // the route to link to when a user clicks a control link
					);
?>
        </div>
      </div>
    </div>
  </div>
</div>
