<!-- CONTENT START HERE -->
<div id="content">
    <div id="banner">
        <ul class="slides">
            <?php if (isset($banners) && is_array($banners) && count($banners) > 0):?>
                <?php foreach ($banners as $banner):?>
                    <li>
                        <img src="<?php echo $banner['banner_url'];?>" alt="<?php echo $banner['title'];?>">
                        <a href="javascript:;" class="play pop-click" data-popup="video">

                        </a>
                    </li>
                <?php endforeach;?>
            <?php endif;?>
            <!--<li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video">

                </a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image2.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image3.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image4.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image5.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image6.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image7.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image8.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>
            <li>
                <img src="https://s3-us-west-2.amazonaws.com/ovessence/img/banner-image9.jpg" alt="">
                <a href="javascript:;" class="play pop-click" data-popup="video"></a>
            </li>-->
        </ul>
        <div class="banner-content">
            <div class="main">
                <?php echo isset($banner_content)?$banner_content:'';?>
            </div>
        </div>
    </div>
    <div class="search main" style="padding-top: 20px;">
        <?php /*
        $search_form->setAttribute('action', $this->url('practitioner', array('action' => 'list')));
        $search_form->prepare();
        echo $this->form()->openTag($search_form);
        ?>
        <ul> 
            <li>
                <?php
                $location = $search_form->get('location');
                echo $this->formInput($location);
                ?>

            </li>
            <li>
                <?php
                $treatment = $search_form->get('treatment');
                echo $this->formSelect($treatment);
                ?>

            </li>
            <li>
                <?php
                $when = $search_form->get('datetime');
                echo $this->formInput($when);
                ?>
                <i class="time icon"></i>						
            </li>
            <li>
                <input type="submit" class="black" value="Search" name="set_filter">

            </li>
        </ul>
        <?php echo $this->form()->closeTag(); */?>
        <div class="searchPractitioner">
            <div class="leftBlack"></div>
            <div class="rightBlack"></div>
            <ul>
                <li class="click"><a href="<?php echo $this->url('practitioner', array('action'=>'list'));?>">Click Here</a></li>
                <li class="searchP"><a href="<?php echo $this->url('practitioner', array('action'=>'list'));?>">Search your practitioner</a></li>
                <li class="click"><a href="<?php echo $this->url('practitioner', array('action'=>'list'));?>">Click Here</a></li>
            </ul>
        </div>
        
    </div>
    <div class="main main-content para common-down">
        <div class="span-82 center">
            <h2 class="fast">
                Videos
                <span>
                    <small></small>
                </span>
            </h2>
            <p class="slow">
                Take control of your health and wellness by viewing before choosing
            </p>
        </div>
        <div id="slider">
                <!--<img src="assets/images/banner.png" alt="">-->
            <?php if (isset($page4) && is_array($page4) && count($page4) > 0): ?>
                <div id="example" class="example pagespan">
                    <div class="scrollbar">
                        <div style="transform: translateZ(0px) translateX(21px); width: 160px;" class="handle">
                            <div class="mousearea"></div>
                        </div>
                    </div>

                    <button class="backward"><i class="icon-angle-left">Prev</i></button>
                    <button class="forward"><i class="icon-angle-right">Next</i></button>

                    <div style="overflow: hidden;" class="frame">
                        <ul class="" style="transform: translateZ(0px) translateX(257px); width: 5538px;">

                            <?php foreach ($page4 as $video):?>
                                <li>
                                    <a>
                                        <iframe id="player_1" style="width:100%" src="//player.vimeo.com/video/<?php echo isset($video['media_url']) ? $video['media_url'] : ''; ?>?api=1&amp;player_id=player_1" width="540" height="304" frameborder="0"></iframe>
                                        <div class="over-lay-text">
                                            <a href="<?php echo $this->url('practitioner', array('action' => 'view', 'id' => $video['user_id']))?>">View Profile</a>
                                            <!--<?php echo $video['media_description']; ?>
                                            <span><?php echo date('Y-m-d', strtotime($video['created_date'])); ?></span>	
                                            <span class="play-button "></span>-->
                                        </div>
                                    </a>
                                </li>
                            <?php endforeach; ?>

                        </ul>
                    </div>
                </div>
            <?php endif; ?>

        </div>
    </div>
    <?php echo str_replace('{{url}}', $this->basePath(), $page1); ?>
    <?php echo str_replace('{{url}}', $this->basePath(), $page2); ?>
    <?php echo str_replace('{{url}}', $this->basePath(), $page3); ?>
</div>
